# ============================================================
# FILE: rliger_online_inmf_mouse_v16_fixed.R
# PURPOSE:
#   Run Online iNMF (rliger) on mouse Tabula Muris Senis (.h5ad),
#   using the frozen canonical HVG list generated by
#   make_mouse_canonical_hvg*.py.
#
# WHY v16:
#   v15 could write an all-NA embedding if rliger returned H/H.norm
#   rownames that did not match AnnData obs_names. The Python benchmark
#   then converted those NAs to zeros, producing degenerate Online_iNMF
#   metrics (e.g., ARI=0, Sil=0, iLISI=1).
#
#   v16 fixes export using the pancreas Online iNMF strategy:
#     - retrieve H as a list or matrix using getMatrix(lig, "H")
#     - coerce each H matrix to cells x k
#     - align by canonical cell IDs when possible
#     - if row/column names are non-canonical but dimensions match,
#       assume rliger preserved order and assign expected cell IDs
#     - stop if alignment fails instead of writing mostly NA output
#     - reorder final embedding to original AnnData obs_names
#
# INPUT:
#   ./Dataset/tabula-muris_sub50k_combined.h5ad
#   ./Benchmark_Mouse_Out/mouse_hvg_canonical.txt
#
# OUTPUT:
#   ./Benchmark_Mouse_Out/X_online_inmf_mouse.csv
#   ./Benchmark_Mouse_Out/online_inmf_mouse_hvg_used.txt
#   ./Benchmark_Mouse_Out/online_inmf_mouse_hvg_used.md5
# ============================================================

suppressPackageStartupMessages({
  library(zellkonverter)        # readH5AD
  library(SingleCellExperiment) # SCE container
  library(Matrix)
  library(rliger)
})

set.seed(0)

# -----------------------------
# CONFIG
# -----------------------------
# Can be overridden from PowerShell/R shell:
#   $env:GENOREFINE_DATASET_ROOT="C:/path/to/MouseDataset"
BASE_DIR <- Sys.getenv(
  "GENOREFINE_DATASET_ROOT",
  unset = getwd()
)
setwd(BASE_DIR)

IN_H5AD <- "./Dataset/tabula-muris_sub50k_combined.h5ad"
OUT_DIR <- "Benchmark_Mouse_Out"
OUT_CSV <- file.path(OUT_DIR, "X_online_inmf_mouse.csv")

CANONICAL_HVG_FILE <- file.path(OUT_DIR, "mouse_hvg_canonical.txt")
CANONICAL_HVG_MD5  <- file.path(OUT_DIR, "mouse_hvg_canonical.md5")

OUT_HVG_USED_TXT <- file.path(OUT_DIR, "online_inmf_mouse_hvg_used.txt")
OUT_HVG_USED_MD5 <- file.path(OUT_DIR, "online_inmf_mouse_hvg_used.md5")

FIXED_BATCH_KEY <- "dataset"
K <- 30
LAMBDA <- 5.0
MIN_GENES_REQUIRED <- 500

# If TRUE, fail if any cells are removed before integration. This prevents
# writing an embedding that Python later treats as valid but partly zero-filled.
STRICT_NO_REMOVED_CELLS <- TRUE

dir.create(OUT_DIR, showWarnings = FALSE, recursive = TRUE)

# -----------------------------
# Helpers
# -----------------------------
get_counts_matrix <- function(sce) {
  assay_names <- assayNames(sce)
  cat("Assays found:", paste(assay_names, collapse = ", "), "\n")
  if ("counts" %in% assay_names) return(assay(sce, "counts"))
  if ("X" %in% assay_names) return(assay(sce, "X"))
  if ("logcounts" %in% assay_names) return(assay(sce, "logcounts"))
  return(assay(sce, assay_names[1]))
}

safe_as_dgC <- function(x) {
  if (!inherits(x, "dgCMatrix")) x <- as(x, "dgCMatrix")
  x
}

compute_gene_md5 <- function(genes) {
  tf <- tempfile(fileext = ".txt")
  writeLines(as.character(genes), tf, useBytes = TRUE)
  md5 <- unname(tools::md5sum(tf))
  unlink(tf)
  md5
}

load_canonical_hvgs <- function(path) {
  if (!file.exists(path)) stop("Canonical HVG file not found: ", path)

  if (grepl("\\.csv$", path, ignore.case = TRUE)) {
    df <- read.csv(path, stringsAsFactors = FALSE, check.names = FALSE)
    genes <- if ("gene" %in% colnames(df)) df$gene else df[[1]]
  } else {
    genes <- readLines(path, warn = FALSE)
  }

  genes <- as.character(genes)
  genes <- trimws(genes)
  genes <- genes[!is.na(genes)]
  genes <- genes[nzchar(genes)]
  genes <- genes[!duplicated(genes)]
  genes
}

# rliger compatibility wrappers
run_online_inmf_compat <- function(lig, k, lambda) {
  out <- NULL

  # rliger v2.x preferred route
  try({
    out <- runIntegration(lig, k = k, lambda = lambda, method = "online")
  }, silent = TRUE)

  # older fallbacks
  if (is.null(out)) {
    try({ out <- runOnlineINMF(lig, k = k, lambda = lambda) }, silent = TRUE)
  }
  if (is.null(out)) {
    try({ out <- online_iNMF(lig, k = k, lambda = lambda) }, silent = TRUE)
  }
  if (is.null(out)) stop("Could not run online iNMF using runIntegration/runOnlineINMF/online_iNMF.")
  out
}

quantile_norm_compat <- function(lig) {
  out <- NULL
  try({ out <- quantileNorm(lig) }, silent = TRUE)
  if (is.null(out)) {
    try({ out <- quantile_norm(lig) }, silent = TRUE)
  }
  if (is.null(out)) stop("Could not run quantile normalization using quantileNorm/quantile_norm.")
  out
}

get_raw_list_compat <- function(lig) {
  out <- NULL
  try({ out <- rawData(lig) }, silent = TRUE)
  if (is.null(out)) {
    try({ out <- getMatrix(lig, "rawData") }, silent = TRUE)
  }
  if (is.null(out) && "raw.data" %in% slotNames(lig)) out <- lig@raw.data
  out
}

get_H_list_compat <- function(lig) {
  # Match pancreas strategy: export H, not a full H_full with NA rows.
  out <- NULL

  try({ out <- getMatrix(lig, "H") }, silent = TRUE)
  if (is.null(out) && "H" %in% slotNames(lig)) {
    try({ out <- lig@H }, silent = TRUE)
  }

  # If H is unavailable, try H.norm as a fallback.
  if (is.null(out)) {
    try({ out <- getMatrix(lig, "H.norm") }, silent = TRUE)
  }
  if (is.null(out) && "H.norm" %in% slotNames(lig)) {
    try({ out <- lig@H.norm }, silent = TRUE)
  }

  if (is.null(out)) stop("Could not retrieve H or H.norm from liger object.")
  if (inherits(out, "list")) return(out)
  list(all = out)
}

coerce_H_to_cells_by_k <- function(h, expected_cells, batch_name) {
  h <- as.matrix(h)
  rn <- rownames(h)
  cn <- colnames(h)
  n_expected <- length(expected_cells)

  assign_factor_names <- function(m) {
    if (is.null(colnames(m)) || any(is.na(colnames(m))) || any(colnames(m) == "")) {
      colnames(m) <- paste0("Factor_", seq_len(ncol(m)))
    }
    m
  }

  # Best case: rows already correspond to expected cell IDs.
  if (!is.null(rn) && all(expected_cells %in% rn)) {
    h <- h[expected_cells, , drop = FALSE]
    h <- assign_factor_names(h)
    return(h)
  }

  # Best case: columns correspond to expected cell IDs, so transpose.
  if (!is.null(cn) && all(expected_cells %in% cn)) {
    h <- t(h[, expected_cells, drop = FALSE])
    rownames(h) <- expected_cells
    h <- assign_factor_names(h)
    return(h)
  }

  # Names exist but are non-canonical. If dimensions match, assume rliger kept order.
  if (nrow(h) == n_expected) {
    if (!is.null(rn) && length(rn) == n_expected && setequal(rn, expected_cells)) {
      h <- h[expected_cells, , drop = FALSE]
    } else {
      message(
        "Warning: H rownames for '", batch_name,
        "' are missing or non-canonical; assuming row order matches expected cell order."
      )
      rownames(h) <- expected_cells
    }
    h <- assign_factor_names(h)
    return(h)
  }

  if (ncol(h) == n_expected) {
    if (!is.null(cn) && length(cn) == n_expected && setequal(cn, expected_cells)) {
      h <- t(h[, expected_cells, drop = FALSE])
    } else {
      message(
        "Warning: H colnames for '", batch_name,
        "' are missing or non-canonical; assuming column order matches expected cell order and transposing."
      )
      h <- t(h)
    }
    rownames(h) <- expected_cells
    h <- assign_factor_names(h)
    return(h)
  }

  stop(
    "Could not align H matrix for '", batch_name, "'. Expected ", n_expected,
    " cells, but H dim=", paste(dim(h), collapse = "x")
  )
}

# -----------------------------
# 1) Load AnnData (.h5ad)
# -----------------------------
cat("Reading:", IN_H5AD, "\n")
sce <- zellkonverter::readH5AD(IN_H5AD, verbose = TRUE)

counts <- get_counts_matrix(sce)
counts <- safe_as_dgC(counts)

md <- as.data.frame(colData(sce))

if (!("dataset" %in% colnames(md))) {
  if ("method" %in% colnames(md)) {
    md$dataset <- as.character(md$method)
  } else if ("technology" %in% colnames(md)) {
    md$dataset <- as.character(md$technology)
  } else {
    stop(
      "Missing fixed batch key 'dataset' and could not infer it from method/technology. Available metadata columns: ",
      paste(colnames(md), collapse = ", ")
    )
  }
}

BATCH_KEY <- FIXED_BATCH_KEY
if (!(BATCH_KEY %in% colnames(md))) {
  stop("Missing fixed batch key: ", BATCH_KEY, ". Available metadata columns: ", paste(colnames(md), collapse = ", "))
}
cat("Using fixed batch key:", BATCH_KEY, "\n")

cell_ids <- colnames(counts)
if (is.null(cell_ids)) stop("Counts matrix has NULL colnames; cannot align embeddings. Ensure AnnData has obs_names.")

gene_names <- rownames(counts)
if (is.null(gene_names)) stop("Counts matrix has NULL rownames; cannot proceed safely.")

rownames(md) <- cell_ids

# -----------------------------
# 2) Split by batch
# -----------------------------
batches <- as.character(md[[BATCH_KEY]])
names(batches) <- cell_ids

batch_levels <- sort(unique(batches))
cat("Number of batches:", length(batch_levels), "\n")
cat("Batch levels:", paste(batch_levels, collapse = ", "), "\n")

if (length(batch_levels) < 2) {
  warning("Only 1 batch level found for key '", BATCH_KEY, "'. Online iNMF will run but this is not a meaningful integration setting.")
}

mat_list <- lapply(batch_levels, function(b) {
  idx <- which(batches == b)
  counts[, idx, drop = FALSE]
})
names(mat_list) <- batch_levels

for (b in names(mat_list)) {
  mat_list[[b]] <- safe_as_dgC(mat_list[[b]])
  rownames(mat_list[[b]]) <- gene_names
  if (is.null(colnames(mat_list[[b]]))) {
    colnames(mat_list[[b]]) <- names(batches)[batches == b]
  }
}

cat("Cells per batch before filtering:\n")
print(sapply(mat_list, ncol))

# -----------------------------
# 3) Load canonical HVGs
# -----------------------------
cat("Loading canonical HVGs from:", CANONICAL_HVG_FILE, "\n")
selected_genes <- load_canonical_hvgs(CANONICAL_HVG_FILE)
cat("Canonical HVGs loaded:", length(selected_genes), "\n")

loaded_md5 <- compute_gene_md5(selected_genes)
cat("Loaded canonical HVG md5:", loaded_md5, "\n")

if (file.exists(CANONICAL_HVG_MD5)) {
  expected_md5 <- readLines(CANONICAL_HVG_MD5, warn = FALSE)
  expected_md5 <- expected_md5[nzchar(expected_md5)][1]
  if (!is.na(expected_md5) && nzchar(expected_md5)) {
    cat("Expected canonical HVG md5:", expected_md5, "\n")
    if (!identical(expected_md5, loaded_md5)) {
      warning("Canonical HVG md5 mismatch. Expected: ", expected_md5, " Loaded: ", loaded_md5)
    }
  }
} else {
  writeLines(loaded_md5, CANONICAL_HVG_MD5)
  cat("Wrote canonical HVG md5 file:", CANONICAL_HVG_MD5, "\n")
}

selected_genes <- selected_genes[selected_genes %in% gene_names]
selected_genes <- unique(as.character(selected_genes))
selected_genes <- selected_genes[!is.na(selected_genes)]
cat("Canonical HVGs present in dataset:", length(selected_genes), "\n")

if (length(selected_genes) < MIN_GENES_REQUIRED) {
  stop("Too few canonical HVGs present in dataset after matching rownames: ", length(selected_genes))
}

for (b in names(mat_list)) {
  mat_list[[b]] <- mat_list[[b]][selected_genes, , drop = FALSE]
}

# Remove cells that have 0 counts across selected genes.
removed_zero_cells <- character(0)
for (b in names(mat_list)) {
  nz <- Matrix::colSums(mat_list[[b]] != 0)
  keep <- (nz > 0)
  if (sum(!keep) > 0) {
    cat("Removing", sum(!keep), "cells with 0 counts across canonical genes in", b, ".\n")
    removed_zero_cells <- c(removed_zero_cells, colnames(mat_list[[b]])[!keep])
    mat_list[[b]] <- mat_list[[b]][, keep, drop = FALSE]
  }
}

if (length(removed_zero_cells) > 0 && STRICT_NO_REMOVED_CELLS) {
  removed_path <- file.path(OUT_DIR, "X_online_inmf_mouse_removed_cells.txt")
  writeLines(removed_zero_cells, removed_path)
  stop(
    "Removed cells were detected before Online iNMF (", length(removed_zero_cells), "). ",
    "This would make the exported embedding incomplete. Removed list written to: ", removed_path
  )
}

empty_batches <- names(mat_list)[vapply(mat_list, ncol, integer(1)) == 0]
if (length(empty_batches) > 0) {
  stop("Some batches became empty after filtering canonical HVGs: ", paste(empty_batches, collapse = ", "))
}

cat("Cells per batch after filtering:\n")
print(sapply(mat_list, ncol))

# Expected cell order per batch and global order. Final export is reordered to
# original AnnData obs_names (cell_ids).
all_cells_by_batch <- lapply(mat_list, colnames)
all_cells_by_batch <- all_cells_by_batch[batch_levels]
all_cells_in_liger_order <- unlist(all_cells_by_batch, use.names = FALSE)
cell_ids_final <- cell_ids[!(cell_ids %in% removed_zero_cells)]

# -----------------------------
# 4) Create liger object + normalize/scale + online iNMF
# -----------------------------
cat("Creating liger object...\n")
lig <- createLiger(mat_list)

raw_list_after <- get_raw_list_compat(lig)
if (!is.null(raw_list_after)) {
  common_genes <- Reduce(intersect, lapply(raw_list_after, rownames))
} else {
  common_genes <- Reduce(intersect, lapply(mat_list, rownames))
}

selected_genes <- selected_genes[selected_genes %in% common_genes]
selected_genes <- unique(as.character(selected_genes))
selected_genes <- selected_genes[!is.na(selected_genes)]
cat("Canonical HVGs present in ALL datasets after createLiger:", length(selected_genes), "\n")

if (length(selected_genes) < MIN_GENES_REQUIRED) {
  stop("Too few canonical HVGs remain after intersecting across datasets: ", length(selected_genes))
}

writeLines(selected_genes, OUT_HVG_USED_TXT)
used_md5 <- compute_gene_md5(selected_genes)
writeLines(used_md5, OUT_HVG_USED_MD5)
cat("Wrote exact HVG list used by rliger:", OUT_HVG_USED_TXT, "\n")
cat("Used HVG md5:", used_md5, "\n")

varFeatures(lig) <- selected_genes
cat("Variable genes set to:", length(varFeatures(lig)), "\n")

if (K >= length(varFeatures(lig))) {
  stop("K (", K, ") must be < number of variable genes (", length(varFeatures(lig)), "). Lower K or increase gene count.")
}

cat("Normalizing...\n")
lig <- normalize(lig)

cat("Scaling...\n")
lig <- scaleNotCenter(lig)

cat("Running online iNMF...\n")
lig <- run_online_inmf_compat(lig, k = K, lambda = LAMBDA)

cat("Quantile normalizing...\n")
lig <- quantile_norm_compat(lig)

# -----------------------------
# 5) Export embedding aligned to original AnnData obs_names
# -----------------------------
cat("Exporting H embedding using strict pancreas-style alignment...\n")

H_raw_list <- get_H_list_compat(lig)

# If H is returned as a list, align each batch. If it is a single matrix,
# align against all expected cells.
if (length(H_raw_list) == length(batch_levels) && !("all" %in% names(H_raw_list))) {
  if (is.null(names(H_raw_list)) || any(names(H_raw_list) == "")) {
    names(H_raw_list) <- batch_levels
  }

  # If names still do not match, but length matches, assume list order follows batch_levels.
  if (!all(batch_levels %in% names(H_raw_list))) {
    message("Warning: H list names do not match batch levels; assuming H list order matches batch_levels.")
    names(H_raw_list) <- batch_levels
  }

  H_list <- list()
  for (b in batch_levels) {
    H_list[[b]] <- coerce_H_to_cells_by_k(
      H_raw_list[[b]],
      expected_cells = all_cells_by_batch[[b]],
      batch_name = b
    )
  }
  H <- do.call(rbind, H_list[batch_levels])
} else {
  H <- coerce_H_to_cells_by_k(
    H_raw_list[[1]],
    expected_cells = all_cells_in_liger_order,
    batch_name = "all_batches"
  )
}

if (is.null(rownames(H))) stop("H has no rownames after coercion; cannot align cells.")

missing <- setdiff(cell_ids_final, rownames(H))
extra <- setdiff(rownames(H), cell_ids_final)

cat("Cells in original AnnData:", length(cell_ids), "\n")
cat("Cells expected after filtering:", length(cell_ids_final), "\n")
cat("Cells in H:", nrow(H), "\n")
cat("Missing cells in H:", length(missing), "\n")
cat("Extra cells in H:", length(extra), "\n")

if (length(missing) > 0) {
  stop("H is missing expected cells. Example missing: ", paste(head(missing, 10), collapse = ", "))
}
if (length(extra) > 0) {
  message("Warning: H has extra cells not expected (showing up to 10): ", paste(head(extra, 10), collapse = ", "))
}

# Reorder to original AnnData obs_names.
H <- H[cell_ids_final, , drop = FALSE]

if (any(!is.finite(H))) {
  stop("Final H contains NA/Inf values. Refusing to write invalid embedding CSV.")
}

if (nrow(H) != length(cell_ids)) {
  stop(
    "Final H row count (", nrow(H), ") does not match original AnnData cells (", length(cell_ids), "). ",
    "This would fail or partially zero-fill in Python."
  )
}

write.csv(H, OUT_CSV, quote = FALSE)
cat("✅ Online iNMF complete using canonical HVGs. Wrote:", OUT_CSV, "\n")
cat("Final embedding dim:", paste(dim(H), collapse = "x"), "\n")
cat("Final embedding variance:", signif(var(as.vector(H)), 6), "\n")
