# Purpose: Run the canonical end-to-end HP-CB pancreas benchmark (legacy code name: HIE).
# Author: Ariana Rahman (Arizona State University)

"""
FILE: bench_hie_master_v6.py
-------------------------------------------------------------------------------
Date: April 2026 (v7)

PURPOSE
    Canonical end-to-end benchmark for the HP-CB pancreas dataset (legacy code
    name: HIE).
    This script is the HIE counterpart of bench_pancreas_multi_master_v9.py and
    produces the same *paper-facing* output artifacts (results CSV, ranked CSV,
    main-metrics table CSV/TEX, and a grouped bar chart), while retaining
    HIE-specific UMAP exports.

    Methods compared (depending on availability):
      - Baselines: Scanorama, Harmony, BBKNN, (optional) Seurat, Online_iNMF, DiffusionMap, PHATE
      - GenoDR refinements: GenoDR(Scanorama), GenoDR(Harmony), (optional) GenoDR(Seurat),
                           GenoDR(Online_iNMF), GenoDR(DiffusionMap), GenoDR(PHATE)

v7 CHANGES
    1) Uses the frozen canonical HIE HVG file generated by make_hie_canonical_hvg.py:
         CFG.out_folder / hie_hvg_canonical.txt
    2) Preserves the clean order when a frozen HVG file is used:
         subset genes first, then normalize/log, then scale/PCA.
    3) Validates and logs the canonical HVG MD5 when hie_hvg_canonical.md5 exists.
    4) Preserves Harmony output orientation compatibility across harmonypy versions.
    5) Adds an in-process Keras/TensorFlow compatibility patch for GenoDR so GenoDR(*)
         methods can run with current Keras behavior.
    6) Uses the same neighbor-representation slicing policy as the pancreas/mouse
         master scripts for clustering consistency.

CONSISTENCY GUARANTEE (Reviewer-facing)
    The benchmark enforces a consistent evaluation protocol across methods:
      - Same frozen feature space across methods when canonical HVGs are used
      - Same downstream preprocessing after feature subsetting
      - Same scaling + PCA baseline (50 PCs) for all methods that start from PCA
      - Same clustering approach (Leiden) using a fixed resolution (CFG.leiden_res)

INPUTS
    Required:
      - CFG.data_file: HIE AnnData (.h5ad)

    Frozen canonical HVG file (used by default, in CFG.out_folder):
      - hie_hvg_canonical.txt

    Optional (external method embeddings saved as CSV into CFG.out_folder):
      - CFG.seurat_csv_name:
            Seurat integration embedding (cells x dims) with row order matching adata.obs_names
      - CFG.online_inmf_csv_name:
            Online iNMF embedding (cells x dims) with row order matching adata.obs_names

OUTPUTS (written to CFG.out_folder)
    Core benchmark outputs (Pancreas-style naming):
      - benchmark_results_hie.csv
            Per-method metrics, runtime, and clustering resolution.
      - benchmark_ranked_hie.csv
            Same as above but sorted by ARI (then Silhouette).
      - table_hie_main.csv
            Paper-facing table with {Method, ARI, Silhouette, iLISI} (no RI).
      - table_hie_main.tex
            LaTeX table for the manuscript (no RI).
      - fig_hie_bars_main_metrics.png
            Grouped bar chart for ARI / Silhouette / iLISI (no RI).

    Visualization exports (HIE-specific, per-method):
      - UMAP_<Method>_class.png
      - UMAP_<Method>_batch.png

NOTES
    - If optional external embeddings are missing, the corresponding methods are skipped.
    - If GenoDR is not available (genodr_pipeline import fails), GenoDR(*) methods are skipped.
-------------------------------------------------------------------------------
"""



import os
import re
import time
import logging
import hashlib
from dataclasses import dataclass
from typing import Dict, Tuple, Optional, List, Any

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import scanpy as sc
import anndata as ad
import scanorama

from sklearn.metrics import adjusted_rand_score, rand_score, silhouette_score
from sklearn.neighbors import NearestNeighbors

# Optional deps
try:
    import bbknn  # type: ignore
except Exception:
    bbknn = None

try:
    import harmonypy as hm  # type: ignore
except Exception:
    hm = None

try:
    import genomap.genoDR as gp  # type: ignore
except Exception:
    gp = None

try:
    import phate  # type: ignore
except Exception:
    phate = None

# Optional kBET (rarely installed by default)
try:
    from scib.metrics import kBET as scib_kbet  # type: ignore
except Exception:
    scib_kbet = None


# -----------------------------
# Config
# -----------------------------
@dataclass
class HieConfig:
    data_file: str = r"./Dataset/human_pancreas_norm_complexBatch.h5ad"
    out_folder: str = "./Benchmark_Hie_Out"
    seed: int = 0

    # external embeddings produced in R
    seurat_csv: str = "./Benchmark_Hie_Out/X_seurat_hie.csv"
    online_inmf_csv: str = "./Benchmark_Hie_Out/X_online_inmf_hie.csv"

    # fixed keys for HIE
    batch_key_fixed: Optional[str] = "tech"
    label_key_fixed: Optional[str] = "celltype"

    # fallback candidates (only used if fixed keys are missing)
    batch_key_candidates: Tuple[str, ...] = (
        "tech", "technology", "platform", "protocol", "method", "batch", "Batch", "dataset", "study",
        "donor", "orig.ident", "source"
    )
    label_key_candidates: Tuple[str, ...] = (
        "celltype", "class", "cell_type", "CellType", "label", "labels", "annotation"
    )

    # preprocess
    do_normalize_log1p: bool = True
    do_hvg: bool = True
    hvg: int = 2000
    hvg_flavor: str = "seurat_v3"

    # fair feature selection across batches
    hvg_union_per_batch: bool = True
    hvg_per_batch: int = 2000
    hvg_union_mode: str = "union"  # union or intersection

    # Frozen canonical HVG file (v6 default path)
    use_canonical_hvg_file: bool = True
    canonical_hvg_file: str = "hie_hvg_canonical.txt"
    canonical_hvg_md5_file: str = "hie_hvg_canonical.md5"
    canonical_hvg_metadata_file: str = "hie_hvg_canonical_metadata.json"
    check_canonical_hvg_md5_file: bool = True
    fallback_to_dynamic_hvgs_if_missing: bool = False
    require_exact_canonical_hvg_match: bool = True

    do_scale: bool = True
    max_scale_value: float = 10.0
    n_pcs: int = 50
    n_neighbors: int = 15

    neighbor_metric: str = "cosine"
    neighbor_n_dims: int = 30
    strict_use_rep: bool = True

    # DiffusionMap parameters
    diffmap_n_comps: int = 30
    diffmap_embed_key: str = "X_diffmap"

    # PHATE parameters
    phate_n_components: int = 30
    phate_knn: int = 15
    phate_decay: int = 40
    phate_t: str = "auto"
    phate_embed_key: str = "X_phate"

    # Leiden tuning
    leiden_target_n_clusters_if_labels_exist: bool = True
    leiden_resolution_default: float = 0.5
    leiden_res_grid: Tuple[float, ...] = tuple(np.round(np.linspace(0.2, 1.6, 15), 2))

    # iLISI
    lisi_k: int = 90

    # GenoDR params
    genodr_dim: int = 32
    genodr_col: int = 33
    genodr_row: int = 33

    # Optional kBET
    run_kbet: bool = False

    # Export embeddings
    export_embeddings: bool = True
    embeddings_folder_name: str = "Embeddings"


CFG = HieConfig()


# -----------------------------
# GenoDR / Keras compatibility
# -----------------------------
_GENODR_PATCH_DONE = False


def ensure_genodr_keras3_compatibility() -> Dict[str, Any]:
    """Patch GenoMap/GenoDR for current Keras behavior inside this process.

    GenoMap 1.3.x builds a Sequential CAE and then queries model.input before
    the model has been called. Current Keras also requires save_weights()
    filenames to end in ``.weights.h5``. This in-memory patch follows the same
    logic used in the mouse master script and avoids editing site-packages.
    """
    global _GENODR_PATCH_DONE

    info: Dict[str, Any] = {
        "patch_attempted": True,
        "patch_applied": False,
        "save_weights_patch_applied": False,
        "details": "",
    }

    if gp is None:
        info["details"] = "genomap.genoDR import unavailable"
        return info

    if _GENODR_PATCH_DONE:
        info["patch_applied"] = True
        info["save_weights_patch_applied"] = True
        info["details"] = "already patched in current process"
        return info

    try:
        import tensorflow as tf
        from tensorflow.keras.layers import Conv2D, Conv2DTranspose, Dense, Flatten, Reshape, Input
        from tensorflow.keras.models import Model
        import genomap.utils.ConvDEC as convdec

        def patched_CAE(input_shape=(28, 28, 1), filters=[32, 64, 128, 10]):
            if input_shape[0] % 8 == 0:
                pad3 = "same"
            else:
                pad3 = "valid"

            x_in = Input(shape=input_shape, name="genodr_input")
            x = Conv2D(filters[0], 15, strides=2, padding="same", activation="relu", name="conv1")(x_in)
            x = Conv2D(filters[1], 5, strides=2, padding="same", activation="relu", name="conv2")(x)
            x = Conv2D(filters[2], 3, strides=2, padding=pad3, activation="relu", name="conv3")(x)
            x = Flatten(name="flatten")(x)
            embedding = Dense(units=filters[3], name="embedding")(x)
            x = Dense(
                units=filters[2] * int(input_shape[0] / 8) * int(input_shape[0] / 8),
                activation="relu",
                name="dense_decode",
            )(embedding)
            x = Reshape(
                (int(input_shape[0] / 8), int(input_shape[0] / 8), filters[2]),
                name="reshape_decode",
            )(x)
            x = Conv2DTranspose(filters[1], 3, strides=2, padding=pad3, activation="relu", name="deconv3")(x)
            x = Conv2DTranspose(filters[0], 5, strides=2, padding="same", activation="relu", name="deconv2")(x)
            x_out = Conv2DTranspose(input_shape[2], 5, strides=2, padding="same", name="deconv1")(x)

            autoencoder = Model(inputs=x_in, outputs=x_out, name="genodr_cae")
            encoder = Model(inputs=x_in, outputs=embedding, name="genodr_encoder")
            return autoencoder, encoder

        convdec.CAE = patched_CAE
        convdec._hie_v7_keras3_patch = True
        info["patch_applied"] = True

        def patch_save_weights(model_cls: Any, flag_name: str) -> bool:
            if getattr(model_cls, flag_name, False):
                return True
            original = model_cls.save_weights

            def compat_save_weights(self, filepath, *args, **kwargs):
                fp = str(filepath)
                patched = fp
                if fp.endswith(".h5") and not fp.endswith(".weights.h5"):
                    patched = fp[:-3] + ".weights.h5"
                    logging.warning(
                        "Patched Keras save_weights filepath for GenoDR compatibility: %s -> %s",
                        fp, patched,
                    )
                return original(self, patched, *args, **kwargs)

            model_cls.save_weights = compat_save_weights
            setattr(model_cls, flag_name, True)
            return True

        ok_tf = patch_save_weights(tf.keras.Model, "_hie_v7_save_weights_patch")
        ok_keras = True
        try:
            import keras
            ok_keras = patch_save_weights(keras.Model, "_hie_v7_save_weights_patch")
        except Exception:
            ok_keras = True

        info["save_weights_patch_applied"] = bool(ok_tf and ok_keras)
        _GENODR_PATCH_DONE = True
        info["details"] = "Applied functional-API CAE patch and save_weights patch for GenoDR compatibility"
        return info

    except Exception as e:
        info["details"] = f"Patch attempt failed: {type(e).__name__}: {e}"
        return info


# -----------------------------
# Utilities
# -----------------------------
def set_all_seeds(seed: int) -> None:
    np.random.seed(seed)


def ensure_out_dir(path: str) -> None:
    os.makedirs(path, exist_ok=True)


def md5_of_list(items: List[str]) -> str:
    h = hashlib.md5()
    for s in items:
        h.update(s.encode("utf-8"))
        h.update(b"\n")
    return h.hexdigest()


def md5_no_trailing_newline(items: List[str]) -> str:
    """MD5 helper matching the R scripts: join genes with LF and no trailing newline."""
    payload = "\n".join(map(str, items)).encode("utf-8")
    return hashlib.md5(payload).hexdigest()


def safe_pkg_version(pkg_name: str, module_name: Optional[str] = None) -> str:
    """Return installed package version for reproducibility logging."""
    try:
        from importlib import metadata as importlib_metadata
        return importlib_metadata.version(pkg_name)
    except Exception:
        try:
            if module_name is None:
                module_name = pkg_name
            mod = __import__(module_name)
            return str(getattr(mod, "__version__", "unknown"))
        except Exception:
            return "unavailable"


def get_genodr_env_info() -> Dict[str, str]:
    """Package environment summary used in GenoDR diagnostics and logs."""
    return {
        "python": f"{os.sys.version_info.major}.{os.sys.version_info.minor}.{os.sys.version_info.micro}",
        "numpy": safe_pkg_version("numpy"),
        "pandas": safe_pkg_version("pandas"),
        "scanpy": safe_pkg_version("scanpy"),
        "anndata": safe_pkg_version("anndata"),
        "tensorflow": safe_pkg_version("tensorflow"),
        "keras": safe_pkg_version("keras"),
        "tf_keras": safe_pkg_version("tf-keras", "tf_keras"),
        "genomap": safe_pkg_version("genomap"),
        "harmonypy": safe_pkg_version("harmonypy"),
        "scanorama": safe_pkg_version("scanorama"),
        "bbknn": safe_pkg_version("bbknn"),
        "phate": safe_pkg_version("phate"),
    }


def log_preprocess_fingerprint(adata: ad.AnnData, tag: str = "BASE") -> None:
    var_names = [str(v) for v in adata.var_names.tolist()]
    obs_names = [str(o) for o in adata.obs_names.tolist()]
    msg = [
        f"[{tag}] n_obs={adata.n_obs}, n_vars={adata.n_vars}",
        f"[{tag}] var_md5={md5_of_list(var_names)}",
        f"[{tag}] obs_md5={md5_of_list(obs_names)}",
    ]
    if "X_pca" in adata.obsm:
        Xp = np.asarray(adata.obsm["X_pca"])
        msg.append(f"[{tag}] X_pca shape={Xp.shape}, var(PC1)={float(np.var(Xp[:, 0])):.6f}")
    if "canonical_hvg_md5" in adata.uns:
        msg.append(f"[{tag}] canonical_hvg_md5={adata.uns['canonical_hvg_md5']}")
    if "canonical_hvg_file" in adata.uns:
        msg.append(f"[{tag}] canonical_hvg_file={adata.uns['canonical_hvg_file']}")
    logging.info("\n".join(msg))


def compute_lisi_python(X: np.ndarray, labels: np.ndarray, k: int = 90) -> float:
    X = np.asarray(X)
    labels = np.asarray(labels)
    n = X.shape[0]
    k = min(int(k), n - 1) if n > 1 else 1

    nn = NearestNeighbors(n_neighbors=k)
    nn.fit(X)
    _, idx = nn.kneighbors(X)

    uniq, enc = np.unique(labels, return_inverse=True)
    n_classes = len(uniq)

    lisi_scores: List[float] = []
    for i in range(n):
        neigh = enc[idx[i]]
        counts = np.bincount(neigh, minlength=n_classes)
        probs = counts / k
        simpson = float(np.sum(probs**2))
        lisi = 1.0 / simpson if simpson > 0 else 1.0
        lisi_scores.append(lisi)

    return float(np.mean(lisi_scores))



def _rep_for_neighbors(adata: ad.AnnData, rep_key: str, n_dims: int) -> str:
    """Return an obsm key safe for neighbors (slice to n_dims if needed)."""
    if rep_key not in adata.obsm:
        raise KeyError(f"Missing embedding '{rep_key}' in adata.obsm")
    X = np.asarray(adata.obsm[rep_key])
    if not np.isfinite(X).all():
        raise ValueError(f"Non-finite values found in embedding '{rep_key}'")
    if n_dims is None or int(n_dims) <= 0 or X.shape[1] <= int(n_dims):
        return rep_key
    key2 = f"{rep_key}__nd{int(n_dims)}"
    if key2 not in adata.obsm or adata.obsm[key2].shape[0] != X.shape[0]:
        adata.obsm[key2] = X[:, : int(n_dims)].copy()
    return key2


def _select_hvgs_per_batch_union(
    adata: ad.AnnData,
    batch_key: str,
    n_top: int,
    flavor: str,
    layer: Optional[str],
    mode: str = "union",
) -> List[str]:
    """Compute HVGs per batch and return union/intersection gene list."""

    def _matrix_from_layer(aobj: ad.AnnData, lyr: Optional[str]):
        return aobj.layers[lyr] if lyr is not None and lyr in aobj.layers else aobj.X

    def _nonzero_gene_mask(aobj: ad.AnnData, lyr: Optional[str]) -> np.ndarray:
        X = _matrix_from_layer(aobj, lyr)
        sums = np.asarray(X.sum(axis=0)).ravel()
        return sums > 0

    def _run_hvg_safe(aobj: ad.AnnData, n_top_local: int, flavor_local: str, lyr: Optional[str], context: str):
        try:
            sc.pp.highly_variable_genes(
                aobj,
                n_top_genes=int(n_top_local),
                flavor=str(flavor_local),
                subset=False,
                layer=lyr,
            )
            return str(flavor_local)
        except ValueError as e:
            msg = str(e)
            if "Bin edges must be unique" not in msg:
                raise
            fallback = "seurat" if str(flavor_local) != "seurat" else "cell_ranger"
            logging.warning(
                "HVG bin-edge issue in %s with flavor=%s; retrying with flavor=%s after removing all-zero genes.",
                context, flavor_local, fallback,
            )
            keep = _nonzero_gene_mask(aobj, lyr)
            if keep.sum() == 0:
                raise ValueError(f"All genes are zero in {context}; cannot compute HVGs.") from e
            trimmed = aobj[:, keep].copy()
            sc.pp.highly_variable_genes(
                trimmed,
                n_top_genes=min(int(n_top_local), trimmed.n_vars),
                flavor=fallback,
                subset=False,
                layer=lyr,
            )
            hv = np.zeros(aobj.n_vars, dtype=bool)
            hv_idx = np.where(keep)[0][trimmed.var["highly_variable"].to_numpy()]
            hv[hv_idx] = True
            aobj.var["highly_variable"] = hv
            return fallback

    if batch_key not in adata.obs:
        raise KeyError(f"Missing batch_key '{batch_key}' in adata.obs")

    batches = adata.obs[batch_key].astype(str)
    all_hvgs: List[set] = []

    for b in sorted(pd.unique(batches)):
        sub = adata[batches == b].copy()
        used_flavor = _run_hvg_safe(sub, int(n_top), str(flavor), layer, context=f"batch={b}")
        hv = sub.var_names[sub.var["highly_variable"].to_numpy()].tolist()
        if len(hv) == 0:
            logging.warning("No HVGs selected for batch=%s using flavor=%s", b, used_flavor)
        all_hvgs.append(set(hv))

    if len(all_hvgs) == 0:
        raise ValueError("No batches available for HVG selection.")

    mode = str(mode).lower()
    if mode == "intersection":
        genes = set.intersection(*all_hvgs)
    else:
        genes = set.union(*all_hvgs)

    genes = [g for g in adata.var_names if g in genes]
    if len(genes) == 0:
        raise ValueError(f"No HVGs remained after per-batch {mode}.")
    return genes



def _read_canonical_hvg_file(txt_path: str) -> List[str]:
    if not os.path.exists(txt_path):
        raise FileNotFoundError(txt_path)

    ser = pd.read_csv(txt_path, header=None).iloc[:, 0].astype(str)
    hvgs: List[str] = []
    seen = set()
    for x in ser.tolist():
        g = str(x).strip()
        if g == "" or g.lower() == "nan":
            continue
        if g not in seen:
            hvgs.append(g)
            seen.add(g)
    if len(hvgs) == 0:
        raise ValueError(f"Canonical HVG file is empty: {txt_path}")
    return hvgs


def _subset_with_frozen_canonical_hvgs(adata: ad.AnnData, cfg: HieConfig) -> ad.AnnData:
    txt_path = os.path.join(cfg.out_folder, cfg.canonical_hvg_file)
    requested_hvgs = _read_canonical_hvg_file(txt_path)

    present = set(adata.var_names.astype(str).tolist())
    matched_hvgs = [g for g in requested_hvgs if g in present]
    missing_count = int(len(requested_hvgs) - len(matched_hvgs))

    if len(matched_hvgs) == 0:
        raise ValueError(f"No canonical HVGs from file matched adata.var_names. File={txt_path}")

    if cfg.require_exact_canonical_hvg_match and len(matched_hvgs) != len(requested_hvgs):
        raise ValueError(
            f"Canonical HVG file match is incomplete. File={txt_path} | "
            f"requested={len(requested_hvgs)} matched={len(matched_hvgs)} missing={missing_count}"
        )

    canonical_md5_master = md5_of_list(matched_hvgs)
    canonical_md5_r_style = md5_no_trailing_newline(matched_hvgs)
    logging.info(
        "Using frozen canonical HVG file: %s | requested=%d matched=%d missing=%d md5_master=%s md5_r_style=%s",
        txt_path,
        len(requested_hvgs),
        len(matched_hvgs),
        missing_count,
        canonical_md5_master,
        canonical_md5_r_style,
    )

    md5_path = os.path.join(cfg.out_folder, cfg.canonical_hvg_md5_file)
    if cfg.check_canonical_hvg_md5_file and os.path.exists(md5_path):
        try:
            expected_md5 = open(md5_path, "r", encoding="utf-8").read().strip().splitlines()[0].strip()
            if expected_md5 and expected_md5 not in (canonical_md5_r_style, canonical_md5_master):
                raise ValueError(
                    f"Canonical HIE HVG MD5 mismatch. File={txt_path} md5_file={md5_path} "
                    f"expected={expected_md5} observed_r_style={canonical_md5_r_style} observed_master={canonical_md5_master}"
                )
            logging.info("Canonical HIE HVG MD5 verified: %s", expected_md5)
        except IndexError:
            logging.warning("Canonical HIE HVG MD5 file exists but is empty: %s", md5_path)
    elif cfg.check_canonical_hvg_md5_file:
        logging.warning("Canonical HIE HVG MD5 file not found: %s", md5_path)

    meta_path = os.path.join(cfg.out_folder, cfg.canonical_hvg_metadata_file)
    if os.path.exists(meta_path):
        logging.info("Canonical HIE HVG metadata file found: %s", meta_path)

    out = adata[:, matched_hvgs].copy()
    out.uns["canonical_hvg_file"] = txt_path
    out.uns["canonical_hvg_md5"] = canonical_md5_master
    out.uns["canonical_hvg_md5_r_style"] = canonical_md5_r_style
    out.uns["canonical_hvg_n_genes"] = int(len(matched_hvgs))
    return out

def _normalize_obs_name(s: str) -> str:
    s = str(s)
    s = re.sub(r"-1$", "", s)
    s = re.sub(r"\.1$", "", s)
    s = s.replace(".", "-")
    return s


def infer_key_from_obs(adata: ad.AnnData, candidates: Tuple[str, ...]) -> Optional[str]:
    for k in candidates:
        if k in adata.obs.columns:
            return k
    return None


def _nan_guard(X: np.ndarray, name: str) -> np.ndarray:
    X = np.asarray(X)
    if not np.isfinite(X).all():
        logging.warning(f"{name}: NaN/Inf found; replacing with 0.")
        X = np.nan_to_num(X, nan=0.0, posinf=0.0, neginf=0.0)
    return X


def sanitize_method_name(name: str) -> str:
    s = name.replace(" ", "_")
    s = s.replace("(", "_").replace(")", "")
    s = s.replace("/", "_").replace("__", "_")
    return s


def export_embedding_csv(adata: ad.AnnData, embed_key: str, out_path: str) -> None:
    X = np.asarray(adata.obsm[embed_key])
    df = pd.DataFrame(X, index=adata.obs_names.astype(str))
    df.to_csv(out_path)
    logging.info(f"Exported embedding '{embed_key}' -> {out_path}  shape={X.shape}")


def load_embedding_csv_align(adata_in: ad.AnnData, csv_path: str, key: str) -> None:
    """Load an external embedding CSV and align rows to adata.obs_names.

    Attempt 1: direct alignment to obs_names
    Attempt 2: normalized-name alignment (handles '-1', '.' vs '-', etc.)
    """
    if not os.path.exists(csv_path):
        raise FileNotFoundError(csv_path)

    df = pd.read_csv(csv_path, index_col=0)

    # Attempt 1: direct match
    df1 = df.reindex(adata_in.obs_names)
    match_rate_1 = float(df1.notna().all(axis=1).mean())
    if match_rate_1 >= 0.999:
        adata_in.obsm[key] = _nan_guard(df1.to_numpy(), f"CSV[{key}]")
        return

    # Attempt 2: normalized match
    obs_norm = pd.Index([_normalize_obs_name(x) for x in adata_in.obs_names.astype(str)])
    df_norm_index = pd.Index([_normalize_obs_name(x) for x in df.index.astype(str)])

    norm_to_row = {}
    dup = set()
    for orig, n in zip(df.index.astype(str), df_norm_index):
        if n in norm_to_row:
            dup.add(n)
        else:
            norm_to_row[n] = orig
    for n in dup:
        norm_to_row.pop(n, None)

    aligned_rows = [norm_to_row.get(n, None) for n in obs_norm]
    ok = [r is not None for r in aligned_rows]
    match_rate_2 = float(sum(ok) / max(1, len(ok)))

    if match_rate_2 >= 0.999:
        df2 = df.loc[aligned_rows].copy()
        df2.index = adata_in.obs_names
        adata_in.obsm[key] = _nan_guard(df2.to_numpy(), f"CSV[{key}]")
        return

    missing_ex = [adata_in.obs_names[i] for i, r in enumerate(aligned_rows) if r is None][:10]
    raise ValueError(
        f"Embedding CSV alignment failed.\n"
        f"CSV: {csv_path}\n"
        f"Attempt1 (direct) match={match_rate_1*100:.2f}%\n"
        f"Attempt2 (normalized) match={match_rate_2*100:.2f}% missing ex={missing_ex}\n"
        f"Fix: ensure CSV rownames match adata.obs_names (or match after removing '-1' and replacing '.' with '-')."
    )


def tune_leiden_resolution_to_target(
    adata: ad.AnnData,
    use_rep: Optional[str],
    target_k: int,
    n_neighbors: int,
    res_grid: List[float],
    key_added: str,
    random_state: int,
) -> float:
    sc.pp.neighbors(adata, use_rep=use_rep, n_neighbors=n_neighbors)

    best_res = float(res_grid[0])
    best_diff = 10**9
    for r in res_grid:
        sc.tl.leiden(adata, resolution=float(r), key_added=key_added, random_state=random_state)
        k = int(adata.obs[key_added].nunique())
        diff = abs(k - int(target_k))
        if diff < best_diff:
            best_diff = diff
            best_res = float(r)
        if diff == 0:
            break

    sc.tl.leiden(adata, resolution=best_res, key_added=key_added, random_state=random_state)
    return best_res


def tune_leiden_resolution_existing_graph(
    adata: ad.AnnData,
    target_k: int,
    res_grid: List[float],
    key_added: str,
    random_state: int,
) -> float:
    best_res = float(res_grid[0])
    best_diff = 10**9

    for r in res_grid:
        sc.tl.leiden(adata, resolution=float(r), key_added=key_added, random_state=random_state)
        k = int(adata.obs[key_added].nunique())
        diff = abs(k - int(target_k))
        if diff < best_diff:
            best_diff = diff
            best_res = float(r)
        if diff == 0:
            break

    sc.tl.leiden(adata, resolution=best_res, key_added=key_added, random_state=random_state)
    return best_res


def save_umap_png(adata: ad.AnnData, color_key: str, out_png: str, title: str) -> None:
    sc.pl.umap(adata, color=color_key, show=False, title=title)
    import matplotlib.pyplot as plt
    plt.savefig(out_png, dpi=300, bbox_inches="tight")
    plt.close()


def confusion_matrix_table(
    adata: ad.AnnData,
    class_key: str,
    cluster_key: str = "leiden",
    normalize: str = "index",
) -> pd.DataFrame:
    return pd.crosstab(
        adata.obs[class_key].astype(str),
        adata.obs[cluster_key].astype(str),
        normalize=normalize,
    )


def save_confusion_heatmap(cm: pd.DataFrame, out_png: str, title: str) -> None:
    import matplotlib.pyplot as plt
    import seaborn as sns
    plt.figure(figsize=(12, 9))
    sns.heatmap(cm, cmap="YlGnBu")
    plt.title(title)
    plt.tight_layout()
    plt.savefig(out_png, dpi=300)
    plt.close()


# -----------------------------
# Data loading + preprocessing
# -----------------------------

def load_hie_base(cfg: HieConfig) -> Tuple[ad.AnnData, str, Optional[str]]:
    if not os.path.exists(cfg.data_file):
        raise FileNotFoundError(f"Could not find: {cfg.data_file}")

    adata = sc.read(cfg.data_file)
    adata.var_names_make_unique()

    if cfg.batch_key_fixed is not None and cfg.batch_key_fixed in adata.obs.columns:
        batch_key = cfg.batch_key_fixed
    else:
        batch_key = infer_key_from_obs(adata, cfg.batch_key_candidates)

    if cfg.label_key_fixed is not None and cfg.label_key_fixed in adata.obs.columns:
        label_key = cfg.label_key_fixed
    else:
        label_key = infer_key_from_obs(adata, cfg.label_key_candidates)

    if batch_key is None:
        raise ValueError(
            f"No batch key found. Expected '{cfg.batch_key_fixed}' or candidates {cfg.batch_key_candidates}. "
            f"Available keys: {list(adata.obs.columns)[:40]}"
        )
    if label_key is None:
        logging.warning(
            f"No label key found. Expected '{cfg.label_key_fixed}' or candidates {cfg.label_key_candidates}. "
            "ARI/RI and class UMAP will be skipped."
        )

    a = adata.copy()

    # normalize metadata names early so downstream preprocessing can use them
    a.obs["batch"] = a.obs[batch_key].astype(str).astype("category")
    if label_key is not None:
        a.obs["class"] = a.obs[label_key].astype(str).astype("category")
    class_msg = f"obs['{label_key}'] -> obs['class']" if label_key is not None else "None"
    logging.info(f"Resolved keys: batch=obs['{batch_key}'] -> obs['batch']; class={class_msg}")

    # v6 clean order:
    # 1) optionally subset to frozen canonical HVGs first
    # 2) then normalize/log for downstream PCA/integration
    used_frozen_hvgs = False
    if cfg.use_canonical_hvg_file:
        try:
            a = _subset_with_frozen_canonical_hvgs(a, cfg)
            used_frozen_hvgs = True
        except FileNotFoundError as e:
            if not cfg.fallback_to_dynamic_hvgs_if_missing:
                raise
            logging.warning("%s -- falling back to dynamic per-batch HVG selection.", str(e))

    has_counts_layer = "counts" in a.layers.keys()
    counts_layer_name: Optional[str] = "counts" if has_counts_layer else None

    if cfg.do_normalize_log1p:
        if counts_layer_name is not None:
            logging.info("Preprocess: normalize_total/log1p on layer='counts' after feature subsetting.")
            sc.pp.normalize_total(a, target_sum=1e4, layer=counts_layer_name)
            sc.pp.log1p(a, layer=counts_layer_name)
            a.X = a.layers[counts_layer_name]
        else:
            logging.info("Preprocess: normalize_total/log1p on a.X (no counts layer).")
            sc.pp.normalize_total(a, target_sum=1e4)
            sc.pp.log1p(a)

    # Dynamic HVG fallback path only if frozen HVGs are not used
    if cfg.do_hvg and not used_frozen_hvgs:
        flavor = str(cfg.hvg_flavor)
        layer_for_hvg = counts_layer_name if counts_layer_name is not None else None
        if flavor == "seurat_v3" and layer_for_hvg is None:
            logging.warning("HVG seurat_v3 requested but no counts layer -> fallback to cell_ranger.")
            flavor = "cell_ranger"

        if cfg.hvg_union_per_batch:
            hvgs = _select_hvgs_per_batch_union(
                a,
                batch_key=batch_key,
                n_top=int(cfg.hvg_per_batch),
                flavor=flavor,
                layer=layer_for_hvg,
                mode=str(cfg.hvg_union_mode),
            )
            a = a[:, hvgs].copy()
            logging.info(
                "Using dynamic per-batch HVGs: mode=%s selected=%d md5=%s",
                str(cfg.hvg_union_mode),
                len(hvgs),
                md5_of_list([str(x) for x in hvgs]),
            )
        else:
            sc.pp.highly_variable_genes(
                a,
                n_top_genes=int(cfg.hvg),
                flavor=flavor,
                subset=True,
                layer=layer_for_hvg,
            )
            logging.info(
                "Using dynamic pooled HVGs: selected=%d md5=%s",
                int(a.n_vars),
                md5_of_list([str(x) for x in a.var_names.tolist()]),
            )

        if counts_layer_name is not None and cfg.do_normalize_log1p:
            a.X = a.layers[counts_layer_name]

    if cfg.do_scale:
        sc.pp.scale(a, max_value=float(cfg.max_scale_value))
    sc.tl.pca(a, n_comps=int(cfg.n_pcs), random_state=int(cfg.seed))

    try:
        load_embedding_csv_align(a, cfg.seurat_csv, key="X_seurat")
        logging.info("Loaded R-exported Seurat embedding: %s", cfg.seurat_csv)
    except Exception as e:
        logging.warning(f"Seurat CSV not loaded (method will be unavailable): {e}")

    try:
        load_embedding_csv_align(a, cfg.online_inmf_csv, key="X_online_inmf")
        logging.info("Loaded R-exported Online iNMF embedding: %s", cfg.online_inmf_csv)
    except Exception as e:
        logging.warning(f"Online iNMF CSV not loaded (method will be unavailable): {e}")

    return a, "batch", ("class" if label_key is not None else None)


# -----------------------------
# Method runners
# -----------------------------
def run_scanorama(adata_in: ad.AnnData) -> Tuple[ad.AnnData, str]:
    a = adata_in.copy()
    batches = list(a.obs["batch"].cat.categories)

    adatas_list = [a[a.obs["batch"] == b].copy() for b in batches]
    corrected = scanorama.correct_scanpy(adatas_list, return_dimred=True)
    out = ad.concat(corrected, join="outer")
    out.obs["batch"] = out.obs["batch"].astype("category")
    if "class" in out.obs:
        out.obs["class"] = out.obs["class"].astype("category")
    return out, "X_scanorama"



def _coerce_embedding_to_nobs_by_dims(
    Z: Any,
    n_obs: int,
    context: str,
) -> np.ndarray:
    """Coerce external embedding output to shape (n_obs, n_dims)."""
    if hasattr(Z, "to_numpy"):
        X = Z.to_numpy()
    else:
        X = np.asarray(Z)

    X = np.asarray(X)
    if X.ndim > 2:
        X = np.squeeze(X)

    if X.ndim == 1:
        if X.shape[0] == int(n_obs):
            X = X[:, None]
        else:
            raise ValueError(
                f"{context}: unexpected 1D embedding shape {X.shape}; expected first axis == n_obs={n_obs}."
            )

    if X.ndim != 2:
        raise ValueError(f"{context}: unexpected embedding ndim={X.ndim}, shape={getattr(X, 'shape', None)}")

    if X.shape[0] == int(n_obs):
        return X
    if X.shape[1] == int(n_obs):
        logging.warning(
            "%s: transposing external embedding from shape %s to (%d, %d)",
            context, tuple(X.shape), int(n_obs), int(X.shape[0]),
        )
        return X.T

    raise ValueError(f"{context}: could not align embedding to n_obs={n_obs}. Got shape={X.shape}.")


def run_harmony(adata_in: ad.AnnData) -> Tuple[ad.AnnData, str]:
    if hm is None:
        raise RuntimeError("harmonypy not installed")

    a = adata_in.copy()
    X_pca = np.asarray(a.obsm["X_pca"])
    ho = hm.run_harmony(X_pca, a.obs, ["batch"])
    X_harmony = _coerce_embedding_to_nobs_by_dims(ho.Z_corr, a.n_obs, "X_harmony")
    a.obsm["X_harmony"] = _nan_guard(X_harmony, "X_harmony")
    return a, "X_harmony"


def run_bbknn(adata_in: ad.AnnData) -> Tuple[ad.AnnData, str]:
    if bbknn is None:
        raise RuntimeError("bbknn not installed")

    a = adata_in.copy()
    bbknn.bbknn(a, batch_key="batch")  # uses X_pca
    return a, "X_pca"


def run_external_embedding(adata_in: ad.AnnData, embed_key: str) -> Tuple[ad.AnnData, str]:
    a = adata_in.copy()
    if embed_key not in a.obsm:
        raise KeyError(f"Missing '{embed_key}' in adata.obsm. Check CSV creation/path.")
    return a, embed_key


def run_diffmap(adata_in: ad.AnnData, cfg: HieConfig) -> Tuple[ad.AnnData, str]:
    """
    DiffusionMap embedding from Scanpy.
    Uses kNN graph built on PCA (X_pca) by default.
    """
    a = adata_in.copy()

    # ensure neighbors graph exists (use PCA with controlled dimensionality)
    use_rep = _rep_for_neighbors(a, "X_pca", int(cfg.neighbor_n_dims))
    sc.pp.neighbors(a, use_rep=use_rep, n_neighbors=int(cfg.n_neighbors), metric=str(cfg.neighbor_metric))
    sc.tl.diffmap(a, n_comps=int(cfg.diffmap_n_comps))
    # Scanpy stores it at a.obsm["X_diffmap"]
    if cfg.diffmap_embed_key not in a.obsm:
        raise KeyError("Expected diffusion map embedding missing at obsm['X_diffmap'].")
    a.obsm[cfg.diffmap_embed_key] = _nan_guard(np.asarray(a.obsm[cfg.diffmap_embed_key]), "X_diffmap")
    return a, cfg.diffmap_embed_key


def run_phate(adata_in: ad.AnnData, cfg: HieConfig) -> Tuple[ad.AnnData, str]:
    """
    PHATE embedding (optional dependency).
    We run PHATE on PCA (X_pca) to keep compute stable and comparable.
    """
    if phate is None:
        raise RuntimeError("phate not installed (pip install phate)")

    a = adata_in.copy()
    use_rep = _rep_for_neighbors(a, "X_pca", int(cfg.neighbor_n_dims))
    X = _nan_guard(np.asarray(a.obsm[use_rep]), "X_pca_for_PHATE")

    ph = phate.PHATE(
        n_components=int(cfg.phate_n_components),
        knn=int(cfg.phate_knn),
        decay=int(cfg.phate_decay),
        t=cfg.phate_t,
        random_state=int(cfg.seed),
        verbose=False,
    )
    Z = ph.fit_transform(X)
    a.obsm[cfg.phate_embed_key] = _nan_guard(np.asarray(Z), "X_phate")
    return a, cfg.phate_embed_key


def run_genodr_on_key(adata_in: ad.AnnData, embed_key: str, out_key: str, cfg: HieConfig) -> Tuple[ad.AnnData, str]:
    if gp is None:
        env = get_genodr_env_info()
        raise RuntimeError(
            "genomap.genoDR not available.\n"
            f"Environment: {env}\n"
            "Install/activate the correct GenoDR environment before rerunning."
        )

    a = adata_in.copy()
    if embed_key not in a.obsm:
        raise KeyError(
            f"Missing embedding '{embed_key}' in obsm for GenoDR. "
            f"Available embeddings: {list(a.obsm.keys())}"
        )

    X = _nan_guard(np.asarray(a.obsm[embed_key]), name=f"genoDR_in[{embed_key}]")
    if X.ndim != 2:
        raise ValueError(f"GenoDR input embedding must be 2D; got shape={X.shape}")

    if "class" in a.obs:
        n_clusters = max(2, int(a.obs["class"].nunique()))
    else:
        n_clusters = 10

    patch_info = ensure_genodr_keras3_compatibility()
    env = get_genodr_env_info()
    logging.info(
        "GenoDR setup for %s: input_shape=%s, dtype=%s, n_clusters=%d, n_dim=%d, col=%d, row=%d, env=%s, patch=%s",
        embed_key, X.shape, X.dtype, n_clusters, int(cfg.genodr_dim), int(cfg.genodr_col), int(cfg.genodr_row), env, patch_info
    )

    try:
        Z = gp.genoDR(
            X,
            n_dim=int(cfg.genodr_dim),
            n_clusters=int(n_clusters),
            colNum=int(cfg.genodr_col),
            rowNum=int(cfg.genodr_row),
        )
    except Exception as e:
        diagnostic = [
            "GenoDR execution failed.",
            f"embed_key={embed_key}",
            f"input_shape={tuple(X.shape)}",
            f"input_dtype={X.dtype}",
            f"n_clusters={n_clusters}",
            f"n_dim={int(cfg.genodr_dim)}",
            f"colNum={int(cfg.genodr_col)}",
            f"rowNum={int(cfg.genodr_row)}",
            f"env={env}",
            f"patch_info={patch_info}",
            f"original_exception={type(e).__name__}: {e}",
        ]
        msg = "\n".join(diagnostic)
        logging.error(msg)
        raise RuntimeError(msg) from e

    Z = _nan_guard(np.asarray(Z), name=f"genoDR_out[{out_key}]")
    if Z.ndim != 2:
        raise ValueError(f"GenoDR output must be 2D; got shape={Z.shape}")
    if Z.shape[0] != a.n_obs:
        raise ValueError(f"GenoDR output row count mismatch: got {Z.shape[0]}, expected {a.n_obs}")

    a.obsm[out_key] = Z
    return a, out_key


# -----------------------------
# Metrics + clustering
# -----------------------------
def cluster_and_score(
    adata: ad.AnnData,
    rep_for_neighbors: Optional[str],
    cfg: HieConfig,
) -> Tuple[float, Dict[str, Any]]:
    cluster_key = "leiden"
    has_labels = "class" in adata.obs

    if rep_for_neighbors is None:
        if has_labels and cfg.leiden_target_n_clusters_if_labels_exist:
            used_res = tune_leiden_resolution_existing_graph(
                adata=adata,
                target_k=int(adata.obs["class"].nunique()),
                res_grid=list(cfg.leiden_res_grid),
                key_added=cluster_key,
                random_state=int(cfg.seed),
            )
        else:
            used_res = float(cfg.leiden_resolution_default)
            sc.tl.leiden(adata, resolution=used_res, key_added=cluster_key, random_state=int(cfg.seed))
    else:
        rep_key_for_neighbors = _rep_for_neighbors(adata, rep_for_neighbors, int(cfg.neighbor_n_dims))
        if has_labels and cfg.leiden_target_n_clusters_if_labels_exist:
            used_res = tune_leiden_resolution_to_target(
                adata=adata,
                use_rep=rep_key_for_neighbors,
                target_k=int(adata.obs["class"].nunique()),
                n_neighbors=int(cfg.n_neighbors),
                res_grid=list(cfg.leiden_res_grid),
                key_added=cluster_key,
                random_state=int(cfg.seed),
            )
        else:
            sc.pp.neighbors(adata, use_rep=_rep_for_neighbors(adata, rep_for_neighbors, int(cfg.neighbor_n_dims)), n_neighbors=int(cfg.n_neighbors), metric=str(cfg.neighbor_metric))
            used_res = float(cfg.leiden_resolution_default)
            sc.tl.leiden(adata, resolution=used_res, key_added=cluster_key, random_state=int(cfg.seed))

    y_pred = adata.obs[cluster_key].astype(str).to_numpy()
    out: Dict[str, Any] = {"LeidenRes": float(used_res)}

    if has_labels:
        y_true = adata.obs["class"].astype(str).to_numpy()
        out["ARI"] = float(adjusted_rand_score(y_true, y_pred))
        out["RI"] = float(rand_score(y_true, y_pred))
    else:
        out["ARI"] = float("nan")
        out["RI"] = float("nan")

    embed_for_sil = rep_for_neighbors if rep_for_neighbors is not None else "X_pca"
    try:
        X = np.asarray(adata.obsm[embed_for_sil])
        out["Silhouette"] = float(silhouette_score(X, y_pred))
    except Exception:
        out["Silhouette"] = float("nan")

    try:
        X = np.asarray(adata.obsm[embed_for_sil])
        out["iLISI"] = float(compute_lisi_python(X, adata.obs["batch"].astype(str).to_numpy(), k=int(cfg.lisi_k)))
    except Exception:
        out["iLISI"] = float("nan")

    if cfg.run_kbet and scib_kbet is not None:
        try:
            kb = scib_kbet(adata, batch_key="batch", label_key="class" if has_labels else None, embed=embed_for_sil)
            out["kBET"] = float(kb) if kb is not None else float("nan")
        except Exception:
            out["kBET"] = float("nan")
    else:
        out["kBET"] = float("nan")

    return float(used_res), out


# -----------------------------
# One method runner
# -----------------------------
def run_one_method(method_name: str, adata_base: ad.AnnData, cfg: HieConfig) -> Dict[str, Any]:
    t0 = time.time()

    if method_name == "Scanorama":
        adata, embed_key = run_scanorama(adata_base)
        rep_for_neighbors = embed_key

    elif method_name == "Harmony":
        adata, embed_key = run_harmony(adata_base)
        rep_for_neighbors = embed_key

    elif method_name == "BBKNN":
        adata, embed_key = run_bbknn(adata_base)
        rep_for_neighbors = None  # bbknn graph; silhouette uses X_pca

    elif method_name == "Seurat":
        adata, embed_key = run_external_embedding(adata_base, "X_seurat")
        rep_for_neighbors = embed_key

    elif method_name == "Online_iNMF":
        adata, embed_key = run_external_embedding(adata_base, "X_online_inmf")
        rep_for_neighbors = embed_key

    elif method_name == "DiffusionMap":
        adata, embed_key = run_diffmap(adata_base, cfg)
        rep_for_neighbors = embed_key

    elif method_name == "PHATE":
        adata, embed_key = run_phate(adata_base, cfg)
        rep_for_neighbors = embed_key

    elif method_name == "GenoDR(Scanorama)":
        ad_scan, scan_key = run_scanorama(adata_base)
        adata, embed_key = run_genodr_on_key(ad_scan, scan_key, "X_genodr_scanorama", cfg)
        rep_for_neighbors = embed_key

    elif method_name == "GenoDR(Harmony)":
        ad_har, har_key = run_harmony(adata_base)
        adata, embed_key = run_genodr_on_key(ad_har, har_key, "X_genodr_harmony", cfg)
        rep_for_neighbors = embed_key

    elif method_name == "GenoDR(Seurat)":
        ad_seu, seu_key = run_external_embedding(adata_base, "X_seurat")
        adata, embed_key = run_genodr_on_key(ad_seu, seu_key, "X_genodr_seurat", cfg)
        rep_for_neighbors = embed_key

    elif method_name == "GenoDR(Online_iNMF)":
        ad_inmf, inmf_key = run_external_embedding(adata_base, "X_online_inmf")
        adata, embed_key = run_genodr_on_key(ad_inmf, inmf_key, "X_genodr_online_inmf", cfg)
        rep_for_neighbors = embed_key

    elif method_name == "GenoDR(DiffusionMap)":
        ad_dm, dm_key = run_diffmap(adata_base, cfg)
        adata, embed_key = run_genodr_on_key(ad_dm, dm_key, "X_genodr_diffmap", cfg)
        rep_for_neighbors = embed_key

    elif method_name == "GenoDR(PHATE)":
        ad_ph, ph_key = run_phate(adata_base, cfg)
        adata, embed_key = run_genodr_on_key(ad_ph, ph_key, "X_genodr_phate", cfg)
        rep_for_neighbors = embed_key

    else:
        raise ValueError(f"Unknown method: {method_name}")

    used_res, metrics = cluster_and_score(adata, rep_for_neighbors=rep_for_neighbors, cfg=cfg)

    # UMAP on the same embedding used for neighbors (or PCA for BBKNN)
    sc.tl.umap(adata, random_state=int(cfg.seed))
    save_umap_png(
        adata,
        "batch",
        os.path.join(cfg.out_folder, f"UMAP_hie_{sanitize_method_name(method_name)}_batch.png"),
        title=f"Hie: {method_name} (batch)",
    )

    if "class" in adata.obs:
        save_umap_png(
            adata,
            "class",
            os.path.join(cfg.out_folder, f"UMAP_hie_{sanitize_method_name(method_name)}_class.png"),
            title=f"Hie: {method_name} (class)",
        )

        cm = confusion_matrix_table(adata, class_key="class", cluster_key="leiden", normalize="index")
        cm.to_csv(os.path.join(cfg.out_folder, f"Confusion_hie_{sanitize_method_name(method_name)}.csv"))
        save_confusion_heatmap(
            cm,
            os.path.join(cfg.out_folder, f"Heatmap_Confusion_hie_{sanitize_method_name(method_name)}.png"),
            title=f"Hie confusion (row-normalized): {method_name}",
        )

    # Export embeddings to CSV
    if cfg.export_embeddings:
        emb_dir = os.path.join(cfg.out_folder, cfg.embeddings_folder_name)
        ensure_out_dir(emb_dir)
        out_emb = os.path.join(emb_dir, f"X_{sanitize_method_name(method_name)}.csv")
        export_embedding_csv(adata, embed_key if method_name != "BBKNN" else "X_pca", out_emb)

    runtime_s = float(time.time() - t0)

    return {
        "Method": method_name,
        "EmbedKey": embed_key if method_name != "BBKNN" else "X_pca",
        "Runtime_s": runtime_s,
        **metrics,
    }


# -----------------------------
# Main
# -----------------------------
def main() -> None:
    sc.settings.verbosity = 0
    logging.basicConfig(level=logging.INFO, format="%(asctime)s - %(levelname)s - %(message)s")

    set_all_seeds(int(CFG.seed))
    ensure_out_dir(CFG.out_folder)

    # dependency warnings
    if hm is None:
        logging.warning("harmonypy not installed -> Harmony and GenoDR(Harmony) will be skipped.")
    if bbknn is None:
        logging.warning("bbknn not installed -> BBKNN will be skipped.")
    if gp is None:
        logging.warning("genomap.genoDR not available -> GenoDR refinements will be skipped.")
    else:
        patch_info = ensure_genodr_keras3_compatibility()
        logging.info("GenoDR compatibility patch: %s", patch_info.get("details", ""))
    if phate is None:
        logging.warning("phate not installed -> PHATE and GenoDR(PHATE) will be skipped. (pip install phate)")
    if CFG.run_kbet and scib_kbet is None:
        logging.warning("kBET requested but scib.metrics.kBET is not available -> kBET will be NaN.")

    logging.info("Runtime Python executable: %s", os.sys.executable)
    logging.info("Package environment: %s", get_genodr_env_info())

    logging.info("Loading HIE dataset + canonical preprocessing ...")
    adata_base, batch_key_norm, class_key_norm = load_hie_base(CFG)

    logging.info(
        f"Base data: n_obs={adata_base.n_obs}, n_vars={adata_base.n_vars}, "
        f"batches={adata_base.obs[batch_key_norm].nunique()}, "
        f"labels={'yes' if class_key_norm is not None else 'no'}"
    )
    log_preprocess_fingerprint(adata_base, tag="BASE")

    # Methods list
    methods = [
        "Scanorama",
        "Harmony",
        "BBKNN",
        "Seurat",
        "Online_iNMF",
        "DiffusionMap",
        "PHATE",
        "GenoDR(Scanorama)",
        "GenoDR(Harmony)",
        "GenoDR(Seurat)",
        "GenoDR(Online_iNMF)",
        "GenoDR(DiffusionMap)",
        "GenoDR(PHATE)",
    ]

    # Filter methods based on deps and available embeddings
    filtered: List[str] = []
    for m in methods:
        if m in ("Harmony", "GenoDR(Harmony)") and hm is None:
            continue
        if m == "BBKNN" and bbknn is None:
            continue
        if m in ("PHATE", "GenoDR(PHATE)") and phate is None:
            continue
        if m in ("GenoDR(Scanorama)", "GenoDR(Harmony)", "GenoDR(Seurat)", "GenoDR(Online_iNMF)", "GenoDR(DiffusionMap)", "GenoDR(PHATE)") and gp is None:
            continue
        if m in ("Seurat", "GenoDR(Seurat)") and "X_seurat" not in adata_base.obsm:
            continue
        if m in ("Online_iNMF", "GenoDR(Online_iNMF)") and "X_online_inmf" not in adata_base.obsm:
            continue
        filtered.append(m)

    logging.info(f"Methods to run: {filtered}")

    results: List[Dict[str, Any]] = []
    for m in filtered:
        logging.info(f"Running method: {m}")
        try:
            res = run_one_method(m, adata_base, CFG)
            results.append(res)
            logging.info(
                f"Done {m}: ARI={res['ARI']:.3f}, RI={res['RI']:.3f}, "
                f"Sil={res['Silhouette']:.3f}, iLISI={res['iLISI']:.3f}, "
                f"LeidenRes={res['LeidenRes']:.2f}, Runtime_s={res['Runtime_s']:.1f}"
            )
        except Exception as e:
            logging.exception(f"FAILED method {m}: {e}")
            results.append({"Method": m, "Error": str(e)})

    # ------------------------------------------------------------------
    # Core benchmark outputs (Pancreas-style naming)
    # ------------------------------------------------------------------
    df_results = pd.DataFrame(results)
    out_results_csv = os.path.join(CFG.out_folder, "benchmark_results_hie.csv")
    df_results.to_csv(out_results_csv, index=False)

    # Ranked view (helps quickly identify the top method)
    sort_cols = [c for c in ["ARI", "Silhouette", "iLISI"] if c in df_results.columns]
    df_ranked = df_results.sort_values(sort_cols, ascending=[False]*len(sort_cols)).reset_index(drop=True)
    out_ranked_csv = os.path.join(CFG.out_folder, "benchmark_ranked_hie.csv")
    df_ranked.to_csv(out_ranked_csv, index=False)

    # Paper-facing main table (no RI to keep consistency with your Pancreas main table)
    main_cols = [c for c in ["Method", "ARI", "Silhouette", "iLISI"] if c in df_ranked.columns]
    df_table = df_ranked[main_cols].copy()
    out_table_csv = os.path.join(CFG.out_folder, "table_hie_main.csv")
    df_table.to_csv(out_table_csv, index=False)

    out_table_tex = os.path.join(CFG.out_folder, "table_hie_main.tex")
    try:
        def _fmt(x):
            try:
                return f"{float(x):.3f}"
            except Exception:
                return str(x)
        with open(out_table_tex, "w", encoding="utf-8") as f:
            f.write(df_table.to_latex(index=False, escape=False, formatters={c: _fmt for c in df_table.columns if c != 'Method'}))
    except Exception as e:
        logging.warning(f"Could not write LaTeX table: {e}")

    # Grouped bar chart (ARI / Silhouette / iLISI)
    try:
        plot_metrics = [m for m in ["ARI", "Silhouette", "iLISI"] if m in df_ranked.columns]
        if len(plot_metrics) >= 2:
            df_plot = df_ranked[["Method"] + plot_metrics].copy()
            x = np.arange(len(df_plot["Method"]))
            width = 0.8 / len(plot_metrics)
            fig, ax = plt.subplots(figsize=(max(8, 0.45 * len(df_plot)), 4.5))
            for j, met in enumerate(plot_metrics):
                vals = pd.to_numeric(df_plot[met], errors='coerce').fillna(0.0).values
                ax.bar(x + (j - (len(plot_metrics)-1)/2)*width, vals, width, label=met)
            ax.set_xticks(x)
            ax.set_xticklabels(df_plot["Method"], rotation=45, ha='right')
            ax.set_ylabel("Score")
            ax.set_title("HIE benchmark: main metrics")
            ax.legend(frameon=False)
            fig.tight_layout()
            out_bar_png = os.path.join(CFG.out_folder, "fig_hie_bars_main_metrics.png")
            fig.savefig(out_bar_png, dpi=300)
            plt.close(fig)
    except Exception as e:
        logging.warning(f"Could not write bar figure: {e}")

    logging.info(f"Saved results: {out_results_csv}")
    logging.info(f"Saved ranked:  {out_ranked_csv}")
    logging.info(f"Saved table:   {out_table_csv}")
    logging.info(f"Saved tex:     {out_table_tex}")


if __name__ == "__main__":
    main()
