# ============================================================
# FILE: rliger_online_inmf_hie_robustness.R
# PURPOSE:
#   Strict Online iNMF (rliger) reruns for HIE robustness perturbations.
#
#   This script reads the exact cell manifests generated by
#   make_hie_robustness_hvg.py and exports one Online iNMF embedding CSV per
#   perturbation condition.
#
# STRICT CANONICAL CONSISTENCY
#   - Uses ./Benchmark_Hie_Out/hie_hvg_canonical.txt.
#   - Requires ./Benchmark_Hie_Out/hie_hvg_canonical.md5 by default.
#   - Preserves canonical HVG order exactly.
#   - Uses fixed batch key 'tech' when present, matching the HIE Python/R files.
#   - Uses the manifest cell_id order for every exported embedding.
#   - Stops if a manifest cell is missing, duplicated, filtered, or unaligned.
#   - Stops if any canonical HVG is missing from the shared feature space.
#
# RUN ORDER
#   1) python make_hie_canonical_hvg.py
#   2) python make_hie_robustness_hvg.py
#   3) Rscript rliger_online_inmf_hie_robustness.R
#
# INPUT
#   ./Dataset/human_pancreas_norm_complexBatch.h5ad
#   ./Benchmark_Hie_Out/hie_hvg_canonical.txt
#   ./Benchmark_Hie_Out/hie_hvg_canonical.md5
#   ./Benchmark_Hie_Out/Robustness_R_Embeddings/cells_*.csv
#
# OUTPUT
#   ./Benchmark_Hie_Out/Robustness_R_Embeddings/X_online_inmf_hie_<condition>.csv
#   ./Benchmark_Hie_Out/Robustness_R_Embeddings/online_inmf_hie_robustness_summary.csv
#   ./Benchmark_Hie_Out/Robustness_R_Embeddings/online_inmf_hie_robustness_hvg_used.txt
#   ./Benchmark_Hie_Out/Robustness_R_Embeddings/online_inmf_hie_robustness_hvg_used.md5
# ============================================================

suppressPackageStartupMessages({
  library(rliger)
  library(Matrix)
  library(zellkonverter)
  library(SingleCellExperiment)
})

set.seed(0)

# ---------------------------
# Config
# ---------------------------
# Optional override from PowerShell/R shell:
#   $env:GENOREFINE_DATASET_ROOT="C:/path/to/HIEDataset"
BASE_DIR <- Sys.getenv(
  "GENOREFINE_DATASET_ROOT",
  unset = getwd()
)
if (dir.exists(BASE_DIR)) {
  setwd(BASE_DIR)
} else {
  message("BASE_DIR not found. Using current working directory: ", getwd())
}

DATA_FILE <- "./Dataset/human_pancreas_norm_complexBatch.h5ad"
OUTPUT_FOLDER <- "./Benchmark_Hie_Out"
ROBUST_DIR <- file.path(OUTPUT_FOLDER, "Robustness_R_Embeddings")
dir.create(ROBUST_DIR, showWarnings = FALSE, recursive = TRUE)

CANONICAL_HVG_FILE <- file.path(OUTPUT_FOLDER, "hie_hvg_canonical.txt")
CANONICAL_HVG_MD5  <- file.path(OUTPUT_FOLDER, "hie_hvg_canonical.md5")

OUT_HVG_USED_TXT <- file.path(ROBUST_DIR, "online_inmf_hie_robustness_hvg_used.txt")
OUT_HVG_USED_MD5 <- file.path(ROBUST_DIR, "online_inmf_hie_robustness_hvg_used.md5")
OUT_SUMMARY_CSV <- file.path(ROBUST_DIR, "online_inmf_hie_robustness_summary.csv")

FIXED_BATCH_KEY <- "tech"
BATCH_KEY_CANDIDATES <- c(
  "tech", "technology", "platform", "protocol", "method", "batch", "Batch",
  "dataset", "study", "donor", "orig.ident", "source"
)

EXPECTED_N_CANONICAL_HVGS <- 2000
REQUIRE_EXACT_CANONICAL_HVG_MATCH <- TRUE
REQUIRE_CANONICAL_MD5_MATCH <- TRUE

K_FACTORS <- 30
LAMBDA <- 5.0
MIN_SHARED_GENES <- 500
MIN_CELLS_PER_BATCH <- 10

# Keep TRUE for strict Python/R alignment. If a condition contains a cell that
# would be removed after canonical-HVG subsetting, the script stops instead of
# writing an incomplete embedding.
STRICT_NO_DROPPED_CELLS <- TRUE
STRICT_NO_ZERO_CELLS <- TRUE

# ---------------------------
# Helpers
# ---------------------------
to_dgC <- function(x) {
  if (!inherits(x, "dgCMatrix")) x <- as(x, "dgCMatrix")
  x
}

pick_key <- function(df, fixed, candidates) {
  if (!is.null(fixed) && fixed %in% colnames(df)) return(fixed)
  for (k in candidates) {
    if (k %in% colnames(df)) return(k)
  }
  return(NA_character_)
}

read_h5ad_compat <- function(path) {
  attempts <- list(
    function() zellkonverter::readH5AD(path, reader = "R", use_hdf5 = TRUE),
    function() zellkonverter::readH5AD(path, use_hdf5 = TRUE),
    function() zellkonverter::readH5AD(path, reader = "R"),
    function() zellkonverter::readH5AD(path)
  )

  errs <- character(0)
  for (fun in attempts) {
    out <- tryCatch(fun(), error = function(e) {
      errs <<- c(errs, conditionMessage(e))
      NULL
    })
    if (!is.null(out)) return(out)
  }
  stop("All zellkonverter::readH5AD() attempts failed.\n", paste(unique(errs), collapse = "\n"))
}

get_counts_matrix <- function(sce) {
  assay_names <- assayNames(sce)
  message("Assays available: ", paste(assay_names, collapse = ", "))
  if ("counts" %in% assay_names) return(assay(sce, "counts"))
  if ("X" %in% assay_names) return(assay(sce, "X"))
  if ("logcounts" %in% assay_names) return(assay(sce, "logcounts"))
  assay(sce, assay_names[1])
}

compute_gene_md5 <- function(genes) {
  genes <- as.character(genes)
  genes <- trimws(genes)
  genes <- genes[!is.na(genes)]
  genes <- genes[nzchar(genes)]
  payload <- paste(genes, collapse = "\n")

  tf <- tempfile(fileext = ".txt")
  con <- file(tf, open = "wb")
  on.exit({
    try(close(con), silent = TRUE)
    unlink(tf)
  }, add = TRUE)

  writeChar(payload, con, eos = NULL, useBytes = TRUE)
  close(con)
  unname(tools::md5sum(tf))
}

read_canonical_hvgs_strict <- function(path) {
  if (!file.exists(path)) stop("Canonical HVG file not found: ", path)

  genes <- readLines(path, warn = FALSE)
  genes <- as.character(genes)
  genes <- trimws(genes)
  genes <- genes[!is.na(genes)]
  genes <- genes[nzchar(genes)]

  if (length(genes) == 0) stop("Canonical HVG file is empty: ", path)

  duplicated_genes <- unique(genes[duplicated(genes)])
  if (length(duplicated_genes) > 0) {
    stop(
      "Canonical HVG file contains duplicate genes. Count=", length(duplicated_genes),
      "; examples: ", paste(head(duplicated_genes, 10), collapse = ", ")
    )
  }

  if (REQUIRE_EXACT_CANONICAL_HVG_MATCH && length(genes) != EXPECTED_N_CANONICAL_HVGS) {
    stop(
      "Expected exactly ", EXPECTED_N_CANONICAL_HVGS,
      " canonical HIE HVGs, but found ", length(genes), " in ", path
    )
  }

  genes
}

validate_canonical_md5 <- function(genes, md5_path) {
  loaded_md5 <- compute_gene_md5(genes)
  message("Loaded canonical HVG md5: ", loaded_md5)

  if (!file.exists(md5_path)) {
    if (REQUIRE_CANONICAL_MD5_MATCH) {
      stop("Canonical HVG md5 file not found: ", md5_path)
    }
    return(loaded_md5)
  }

  expected_md5 <- readLines(md5_path, warn = FALSE)
  expected_md5 <- expected_md5[nzchar(expected_md5)][1]
  if (is.na(expected_md5) || !nzchar(expected_md5)) {
    if (REQUIRE_CANONICAL_MD5_MATCH) {
      stop("Canonical HVG md5 file is empty: ", md5_path)
    }
    return(loaded_md5)
  }

  message("Expected canonical HVG md5: ", expected_md5)
  if (!identical(expected_md5, loaded_md5)) {
    msg <- paste0("Canonical HVG md5 mismatch. Expected=", expected_md5, " Loaded=", loaded_md5)
    if (REQUIRE_CANONICAL_MD5_MATCH) stop(msg)
    warning(msg)
  }

  loaded_md5
}

get_var_features_compat <- function(lig) {
  out <- NULL
  try({ out <- varFeatures(lig) }, silent = TRUE)
  if (is.null(out) && "var.genes" %in% slotNames(lig)) out <- lig@var.genes
  out <- unique(as.character(out))
  out <- out[!is.na(out)]
  out
}

set_var_features_compat <- function(lig, genes) {
  genes <- as.character(genes)
  genes <- genes[!is.na(genes)]
  ok <- FALSE
  try({ varFeatures(lig) <- genes; ok <- TRUE }, silent = TRUE)
  if (!ok && "var.genes" %in% slotNames(lig)) {
    lig@var.genes <- genes
    ok <- TRUE
  }
  if (!ok) stop("Could not set variable features on liger object.")
  lig
}

get_raw_list_compat <- function(lig) {
  out <- NULL
  try({ out <- rawData(lig) }, silent = TRUE)
  if (is.null(out)) try({ out <- getMatrix(lig, "rawData") }, silent = TRUE)
  if (is.null(out) && "raw.data" %in% slotNames(lig)) out <- lig@raw.data
  out
}

run_online_inmf_compat <- function(lig, k, lambda) {
  out <- NULL

  # rliger v2.x preferred route.
  try({ out <- runIntegration(lig, k = k, lambda = lambda, method = "online") }, silent = TRUE)

  # Older fallbacks.
  if (is.null(out)) try({ out <- runOnlineINMF(lig, k = k, lambda = lambda) }, silent = TRUE)
  if (is.null(out)) try({ out <- online_iNMF(lig, k = k, lambda = lambda) }, silent = TRUE)
  if (is.null(out)) stop("Could not run online iNMF using runIntegration/runOnlineINMF/online_iNMF.")
  out
}

quantile_norm_compat <- function(lig) {
  out <- NULL
  try({ out <- quantileNorm(lig) }, silent = TRUE)
  if (is.null(out)) try({ out <- quantile_norm(lig) }, silent = TRUE)
  if (is.null(out)) stop("Could not run quantile normalization using quantileNorm/quantile_norm.")
  out
}

get_H_list_compat <- function(lig) {
  out <- NULL
  try({ out <- getMatrix(lig, "H") }, silent = TRUE)
  if (is.null(out) && "H" %in% slotNames(lig)) try({ out <- lig@H }, silent = TRUE)

  # Some rliger versions expose only H.norm after quantile normalization.
  if (is.null(out)) try({ out <- getMatrix(lig, "H.norm") }, silent = TRUE)
  if (is.null(out) && "H.norm" %in% slotNames(lig)) try({ out <- lig@H.norm }, silent = TRUE)

  if (is.null(out)) stop("Could not retrieve H or H.norm from liger object.")
  if (inherits(out, "list")) return(out)
  list(all = out)
}

coerce_H_to_cells_by_k <- function(h, expected_cells, batch_name) {
  h <- as.matrix(h)
  rn <- rownames(h)
  cn <- colnames(h)
  n_expected <- length(expected_cells)

  assign_factor_names <- function(m) {
    if (is.null(colnames(m)) || any(is.na(colnames(m))) || any(colnames(m) == "")) {
      colnames(m) <- paste0("Factor_", seq_len(ncol(m)))
    }
    m
  }

  # Best case: rows are cell IDs.
  if (!is.null(rn) && all(expected_cells %in% rn)) {
    h <- h[expected_cells, , drop = FALSE]
    return(assign_factor_names(h))
  }

  # Best case: columns are cell IDs; transpose to cells x factors.
  if (!is.null(cn) && all(expected_cells %in% cn)) {
    h <- t(h[, expected_cells, drop = FALSE])
    rownames(h) <- expected_cells
    return(assign_factor_names(h))
  }

  # If names are missing/non-canonical but dimensions match, assume rliger kept order.
  if (nrow(h) == n_expected) {
    if (!is.null(rn) && length(rn) == n_expected && setequal(rn, expected_cells)) {
      h <- h[expected_cells, , drop = FALSE]
    } else {
      message(
        "Warning: H rownames for batch '", batch_name,
        "' are missing or non-canonical; assuming row order matches expected cell order."
      )
      rownames(h) <- expected_cells
    }
    return(assign_factor_names(h))
  }

  if (ncol(h) == n_expected) {
    if (!is.null(cn) && length(cn) == n_expected && setequal(cn, expected_cells)) {
      h <- t(h[, expected_cells, drop = FALSE])
    } else {
      message(
        "Warning: H colnames for batch '", batch_name,
        "' are missing or non-canonical; assuming column order matches expected cell order and transposing."
      )
      h <- t(h)
    }
    rownames(h) <- expected_cells
    return(assign_factor_names(h))
  }

  stop(
    "Could not align H matrix for batch '", batch_name, "'. Expected ", n_expected,
    " cells, but H dim=", paste(dim(h), collapse = "x")
  )
}

context_from_manifest_path <- function(path) {
  sub("^cells_", "", tools::file_path_sans_ext(basename(path)))
}

safe_summary_value <- function(x) {
  if (length(x) == 0) return(NA_character_)
  paste(names(x), as.integer(x), sep = ":", collapse = ";")
}

# ---------------------------
# Load HIE .h5ad and split into full batch matrices
# ---------------------------
load_hie_full_mats <- function() {
  message("Reading H5AD: ", DATA_FILE)
  if (!file.exists(DATA_FILE)) stop("Missing file: ", DATA_FILE)

  sce <- read_h5ad_compat(DATA_FILE)
  expr <- get_counts_matrix(sce)
  expr <- to_dgC(expr)

  meta <- as.data.frame(colData(sce))
  cell_ids <- colnames(expr)
  if (is.null(cell_ids)) stop("No cell IDs (colnames) found. Cannot align to Python manifests.")
  row.names(meta) <- cell_ids

  gene_ids <- rownames(expr)
  if (is.null(gene_ids)) stop("No gene IDs (rownames) found. Cannot proceed safely.")

  if (any(duplicated(cell_ids))) {
    stop("Duplicate cell IDs found in HIE .h5ad. Strict robustness requires unique obs_names.")
  }
  if (any(duplicated(gene_ids))) {
    stop("Duplicate gene IDs found in HIE .h5ad. Run/inspect var_names_make_unique in Python first.")
  }

  batch_key <- pick_key(meta, FIXED_BATCH_KEY, BATCH_KEY_CANDIDATES)
  if (is.na(batch_key)) {
    stop(
      "Could not detect a batch key in colData. Tried fixed='", FIXED_BATCH_KEY,
      "' and candidates: ", paste(BATCH_KEY_CANDIDATES, collapse = ", "),
      "\nAvailable colData keys (first 40): ", paste(head(colnames(meta), 40), collapse = ", ")
    )
  }
  message("Using batch key: ", batch_key)

  batch_vals <- as.character(meta[[batch_key]])
  if (any(is.na(batch_vals))) stop("Batch column has NA values; please clean or choose another batch key.")
  names(batch_vals) <- cell_ids

  batch_levels <- unique(batch_vals)
  message("Detected batches: ", length(batch_levels))
  message("Batch levels: ", paste(batch_levels, collapse = ", "))

  mat_list <- list()
  for (b in batch_levels) {
    idx <- which(batch_vals == b)
    if (length(idx) == 0) next

    m <- expr[, idx, drop = FALSE]
    m <- to_dgC(m)
    rownames(m) <- gene_ids
    if (is.null(colnames(m))) colnames(m) <- cell_ids[idx]

    mat_list[[b]] <- m
  }

  if (length(mat_list) < 2) stop("Need >=2 batches for online iNMF. Found: ", length(mat_list))

  message("Cells per full batch:")
  print(sapply(mat_list, ncol))

  list(
    expr = expr,
    meta = meta,
    cell_ids = cell_ids,
    gene_ids = gene_ids,
    batch_vals = batch_vals,
    batch_key = batch_key,
    mat_list = mat_list
  )
}

# ---------------------------
# Canonical HVG enforcement
# ---------------------------
apply_canonical_hvgs_to_full_mats <- function(mat_list, canonical_genes) {
  gene_sets <- lapply(mat_list, rownames)
  shared_genes <- Reduce(intersect, gene_sets)
  shared_genes <- unique(as.character(shared_genes))
  shared_genes <- shared_genes[!is.na(shared_genes)]
  message("Shared genes across full batches: ", length(shared_genes))

  if (length(shared_genes) < MIN_SHARED_GENES) {
    stop("Too few shared genes across batches: ", length(shared_genes), " (MIN_SHARED_GENES=", MIN_SHARED_GENES, ")")
  }

  missing_canonical <- setdiff(canonical_genes, shared_genes)
  if (REQUIRE_EXACT_CANONICAL_HVG_MATCH && length(missing_canonical) > 0) {
    stop(
      "Canonical HVGs missing from shared feature space. Missing=", length(missing_canonical),
      "; examples: ", paste(head(missing_canonical, 10), collapse = ", ")
    )
  }

  selected_genes <- canonical_genes[canonical_genes %in% shared_genes]
  if (REQUIRE_EXACT_CANONICAL_HVG_MATCH && length(selected_genes) != length(canonical_genes)) {
    stop(
      "Canonical HVG list was not fully preserved after shared-gene filtering. Canonical=",
      length(canonical_genes), " selected=", length(selected_genes)
    )
  }
  if (length(selected_genes) < MIN_SHARED_GENES) {
    stop("Too few canonical HVGs matched shared feature space: ", length(selected_genes))
  }

  mat_list <- lapply(mat_list, function(m) m[selected_genes, , drop = FALSE])
  list(mat_list = mat_list, selected_genes = selected_genes)
}

# ---------------------------
# Manifest subsetting
# ---------------------------
subset_mats_to_manifest <- function(mat_list, manifest_path, batch_by_cell, ctx) {
  manifest <- read.csv(manifest_path, stringsAsFactors = FALSE)
  if (!"cell_id" %in% colnames(manifest)) stop("Manifest lacks cell_id column: ", manifest_path)

  keep_cells <- as.character(manifest$cell_id)
  keep_cells <- trimws(keep_cells)

  if (any(is.na(keep_cells)) || any(!nzchar(keep_cells))) {
    stop("Manifest has empty/NA cell_id values: ", manifest_path)
  }
  if (any(duplicated(keep_cells))) {
    dups <- unique(keep_cells[duplicated(keep_cells)])
    stop("Manifest has duplicate cell_id values. Examples: ", paste(head(dups, 10), collapse = ", "))
  }

  missing_from_data <- setdiff(keep_cells, names(batch_by_cell))
  if (length(missing_from_data) > 0) {
    stop(
      "Manifest contains cell IDs absent from HIE .h5ad. Missing=", length(missing_from_data),
      "; examples: ", paste(head(missing_from_data, 10), collapse = ", ")
    )
  }

  data_batch <- as.character(batch_by_cell[keep_cells])
  if ("batch" %in% colnames(manifest)) {
    manifest_batch <- as.character(manifest$batch)
    mismatch <- which(manifest_batch != data_batch)
    if (length(mismatch) > 0) {
      i <- mismatch[1]
      stop(
        "Manifest batch column does not match HIE metadata for ", length(mismatch), " cells. ",
        "First mismatch cell=", keep_cells[i],
        " manifest_batch=", manifest_batch[i],
        " data_batch=", data_batch[i]
      )
    }
  } else {
    manifest$batch <- data_batch
  }

  batches_in_manifest <- unique(as.character(manifest$batch))
  cond <- list()

  for (b in batches_in_manifest) {
    if (!(b %in% names(mat_list))) {
      stop("Manifest batch '", b, "' is absent from loaded HIE matrices.")
    }

    cells_b <- keep_cells[as.character(manifest$batch) == b]
    missing_b <- setdiff(cells_b, colnames(mat_list[[b]]))
    if (length(missing_b) > 0) {
      stop(
        "Cells assigned to batch '", b, "' are missing from that batch matrix. Examples: ",
        paste(head(missing_b, 10), collapse = ", ")
      )
    }

    if (length(cells_b) < MIN_CELLS_PER_BATCH) {
      msg <- paste0(
        "Batch '", b, "' has only ", length(cells_b), " manifest cells (<",
        MIN_CELLS_PER_BATCH, ") in condition ", ctx, "."
      )
      if (STRICT_NO_DROPPED_CELLS) stop(msg)
      message(msg, " Dropping this batch because STRICT_NO_DROPPED_CELLS=FALSE.")
      next
    }

    cond[[b]] <- mat_list[[b]][, cells_b, drop = FALSE]
  }

  if (length(cond) < 2) stop("Need >=2 usable batches for condition '", ctx, "'. Found: ", length(cond))

  zero_cells <- character(0)
  for (b in names(cond)) {
    nz <- Matrix::colSums(cond[[b]] != 0)
    if (any(nz == 0)) {
      zero_b <- colnames(cond[[b]])[nz == 0]
      zero_cells <- c(zero_cells, zero_b)
      if (!STRICT_NO_ZERO_CELLS) {
        message("Removing ", length(zero_b), " zero-count cells in ", b, " because STRICT_NO_ZERO_CELLS=FALSE.")
        cond[[b]] <- cond[[b]][, nz > 0, drop = FALSE]
      }
    }
  }

  if (length(zero_cells) > 0) {
    removed_path <- file.path(ROBUST_DIR, paste0("X_online_inmf_hie_removed_zero_cells_", ctx, ".txt"))
    writeLines(zero_cells, removed_path)
    if (STRICT_NO_ZERO_CELLS) {
      stop(
        "Condition '", ctx, "' contains ", length(zero_cells),
        " cells with zero counts across canonical HVGs. Wrote list to ", removed_path,
        ". Regenerate canonical HVGs or relax STRICT_NO_ZERO_CELLS only if Python is updated to use the same subset."
      )
    }
  }

  invalid_after <- names(cond)[sapply(cond, ncol) < MIN_CELLS_PER_BATCH]
  if (length(invalid_after) > 0) {
    msg <- paste0(
      "Condition '", ctx, "' has batches below MIN_CELLS_PER_BATCH after filtering: ",
      paste(invalid_after, collapse = ", ")
    )
    if (STRICT_NO_DROPPED_CELLS) stop(msg)
    cond <- cond[setdiff(names(cond), invalid_after)]
  }

  condition_cells <- keep_cells[keep_cells %in% unlist(lapply(cond, colnames), use.names = FALSE)]
  if (STRICT_NO_DROPPED_CELLS && length(condition_cells) != length(keep_cells)) {
    dropped <- setdiff(keep_cells, condition_cells)
    stop(
      "Condition '", ctx, "' would drop cells before Online iNMF. Dropped=", length(dropped),
      "; examples: ", paste(head(dropped, 10), collapse = ", ")
    )
  }

  list(mat_list = cond, cells = condition_cells, manifest = manifest)
}

# ---------------------------
# Online iNMF per condition
# ---------------------------
run_online_condition <- function(cond_mat_list, condition_cells, ctx, manifest_path, out_csv, selected_genes) {
  t0 <- Sys.time()

  message("Creating liger object for condition '", ctx, "' ...")
  lig <- createLiger(cond_mat_list)

  raw_list_after <- get_raw_list_compat(lig)
  if (!is.null(raw_list_after)) {
    common_genes_after <- Reduce(intersect, lapply(raw_list_after, rownames))
  } else {
    common_genes_after <- Reduce(intersect, lapply(cond_mat_list, rownames))
  }
  common_genes_after <- unique(as.character(common_genes_after))
  common_genes_after <- common_genes_after[!is.na(common_genes_after)]

  missing_after <- setdiff(selected_genes, common_genes_after)
  if (REQUIRE_EXACT_CANONICAL_HVG_MATCH && length(missing_after) > 0) {
    stop(
      "Canonical selected genes are missing after LIGER object creation for condition '", ctx,
      "'. Missing=", length(missing_after), "; examples: ", paste(head(missing_after, 10), collapse = ", ")
    )
  }

  selected_use <- selected_genes[selected_genes %in% common_genes_after]
  if (REQUIRE_EXACT_CANONICAL_HVG_MATCH && length(selected_use) != length(selected_genes)) {
    stop(
      "Canonical HVG order/count was not preserved for condition '", ctx,
      "'. Expected=", length(selected_genes), " selected=", length(selected_use)
    )
  }
  if (length(selected_use) < MIN_SHARED_GENES) {
    stop("Too few canonical genes remain after LIGER object creation for condition '", ctx, "': ", length(selected_use))
  }

  lig <- set_var_features_compat(lig, selected_use)
  var_genes_now <- get_var_features_compat(lig)
  missing_var_features <- setdiff(selected_use, var_genes_now)
  if (length(missing_var_features) > 0) {
    stop(
      "Could not set all canonical variable features for condition '", ctx,
      "'. Missing=", length(missing_var_features), "; examples: ", paste(head(missing_var_features, 10), collapse = ", ")
    )
  }

  if (K_FACTORS >= length(var_genes_now)) {
    stop("K_FACTORS (", K_FACTORS, ") must be < number of variable genes (", length(var_genes_now), ").")
  }

  message("normalize() ...")
  lig <- normalize(lig)

  message("scaleNotCenter() ...")
  lig <- scaleNotCenter(lig)

  message("Online iNMF(k=", K_FACTORS, ", lambda=", LAMBDA, ") ...")
  lig <- run_online_inmf_compat(lig, k = K_FACTORS, lambda = LAMBDA)

  message("Quantile normalization ...")
  lig <- quantile_norm_compat(lig)

  message("Exporting H/H.norm embedding for condition '", ctx, "' ...")
  H_raw_list <- get_H_list_compat(lig)

  batch_names_used <- names(cond_mat_list)
  all_cells_by_batch <- lapply(cond_mat_list, colnames)
  all_cells_by_batch <- all_cells_by_batch[batch_names_used]
  all_cells_in_liger_order <- unlist(all_cells_by_batch, use.names = FALSE)

  if (length(H_raw_list) == length(batch_names_used) && !("all" %in% names(H_raw_list))) {
    if (is.null(names(H_raw_list)) || any(names(H_raw_list) == "")) {
      names(H_raw_list) <- batch_names_used
    }

    if (!all(batch_names_used %in% names(H_raw_list))) {
      if (length(H_raw_list) == length(batch_names_used)) {
        message("Warning: H list names do not match batch names; assuming H list order matches condition batch order.")
        names(H_raw_list) <- batch_names_used
      } else {
        stop("LIGER H list does not contain all condition batches: ", paste(setdiff(batch_names_used, names(H_raw_list)), collapse = ", "))
      }
    }

    H_list <- list()
    for (b in batch_names_used) {
      H_list[[b]] <- coerce_H_to_cells_by_k(
        H_raw_list[[b]],
        expected_cells = all_cells_by_batch[[b]],
        batch_name = b
      )
    }
    H <- do.call(rbind, H_list[batch_names_used])
  } else {
    H <- coerce_H_to_cells_by_k(
      H_raw_list[[1]],
      expected_cells = all_cells_in_liger_order,
      batch_name = "all_batches"
    )
  }

  if (is.null(rownames(H))) stop("H has no rownames after coercion; cannot align cells.")

  missing <- setdiff(condition_cells, rownames(H))
  extra <- setdiff(rownames(H), condition_cells)

  message("Manifest cells: ", length(condition_cells))
  message("Cells in H: ", nrow(H))
  message("Missing cells in H: ", length(missing))
  message("Extra cells in H: ", length(extra))

  if (length(missing) > 0) {
    stop("H is missing condition cells for '", ctx, "'. Examples: ", paste(head(missing, 10), collapse = ", "))
  }
  if (length(extra) > 0) {
    stop("H has extra cells for condition '", ctx, "'. Examples: ", paste(head(extra, 10), collapse = ", "))
  }

  H <- H[condition_cells, , drop = FALSE]

  if (any(!is.finite(H))) {
    stop("Final H contains NA/Inf values for condition '", ctx, "'. Refusing to write invalid embedding CSV.")
  }
  if (any(duplicated(rownames(H)))) {
    stop("Final H contains duplicate rownames for condition '", ctx, "'.")
  }
  if (nrow(H) != length(condition_cells)) {
    stop(
      "Final H row count (", nrow(H), ") does not match condition manifest cells (", length(condition_cells), ") for '", ctx, "'."
    )
  }

  write.csv(H, out_csv, quote = FALSE)
  runtime_s <- as.numeric(difftime(Sys.time(), t0, units = "secs"))

  message("Wrote ", out_csv, " rows=", nrow(H), " cols=", ncol(H))
  message("Embedding variance: ", signif(var(as.vector(H)), 6))

  batch_counts <- sapply(cond_mat_list, ncol)
  list(
    Context = ctx,
    ManifestCSV = manifest_path,
    OutputCSV = out_csv,
    NCells = nrow(H),
    NFactors = ncol(H),
    NBatches = length(cond_mat_list),
    BatchCounts = safe_summary_value(batch_counts),
    NHVGs = length(selected_use),
    KFactors = K_FACTORS,
    Lambda = LAMBDA,
    Runtime_s = runtime_s,
    EmbeddingVariance = var(as.vector(H))
  )
}

# ---------------------------
# Main
# ---------------------------
message("Loading HIE full matrices ...")
loaded <- load_hie_full_mats()

message("Loading canonical HIE HVGs from: ", CANONICAL_HVG_FILE)
canonical_genes <- read_canonical_hvgs_strict(CANONICAL_HVG_FILE)
message("Canonical HVGs loaded: ", length(canonical_genes))
canonical_md5 <- validate_canonical_md5(canonical_genes, CANONICAL_HVG_MD5)

canon <- apply_canonical_hvgs_to_full_mats(loaded$mat_list, canonical_genes)
mat_list <- canon$mat_list
selected_genes <- canon$selected_genes

used_md5 <- compute_gene_md5(selected_genes)
if (REQUIRE_EXACT_CANONICAL_HVG_MATCH && !identical(canonical_md5, used_md5)) {
  stop("Selected HVG md5 differs from canonical md5 despite strict mode. Canonical=", canonical_md5, " selected=", used_md5)
}
writeLines(selected_genes, OUT_HVG_USED_TXT)
writeLines(used_md5, OUT_HVG_USED_MD5)
message("Wrote exact HVG audit files:")
message("  ", OUT_HVG_USED_TXT)
message("  ", OUT_HVG_USED_MD5)

manifest_files <- list.files(ROBUST_DIR, pattern = "^cells_.*\\.csv$", full.names = TRUE)
manifest_files <- sort(manifest_files)
if (length(manifest_files) == 0) {
  stop("No cell manifests found in ", ROBUST_DIR, ". Run make_hie_robustness_hvg.py first.")
}

message("Found ", length(manifest_files), " robustness manifest(s).")
summary_rows <- list()

for (manifest_path in manifest_files) {
  ctx <- context_from_manifest_path(manifest_path)
  out_csv <- file.path(ROBUST_DIR, paste0("X_online_inmf_hie_", ctx, ".csv"))

  message("\n=== Online iNMF HIE condition: ", ctx, " ===")
  cond <- subset_mats_to_manifest(
    mat_list = mat_list,
    manifest_path = manifest_path,
    batch_by_cell = loaded$batch_vals,
    ctx = ctx
  )

  row <- run_online_condition(
    cond_mat_list = cond$mat_list,
    condition_cells = cond$cells,
    ctx = ctx,
    manifest_path = manifest_path,
    out_csv = out_csv,
    selected_genes = selected_genes
  )
  summary_rows[[length(summary_rows) + 1]] <- row
}

summary_df <- do.call(rbind, lapply(summary_rows, function(x) as.data.frame(x, stringsAsFactors = FALSE)))
write.csv(summary_df, OUT_SUMMARY_CSV, row.names = FALSE, quote = FALSE)

message("\n✅ Strict HIE Online iNMF robustness reruns complete.")
message("Summary: ", OUT_SUMMARY_CSV)
message("Batch key used: ", loaded$batch_key)
message("Canonical/used HVG md5: ", used_md5)
