# ============================================================
# Purpose: Generate the Online iNMF comparison embedding for the HP-CB benchmark.
# Author: Ariana Rahman (Arizona State University)
# FILE: rliger_online_inmf_hie_canonical_v8.R
# PURPOSE:
#   Run Online iNMF (rliger) on the HIE .h5ad benchmark using the
#   frozen canonical HVG list generated by make_hie_canonical_hvg.py.
#
# WHY v8:
#   - Uses the canonical HIE HVG artifacts:
#       Benchmark_Hie_Out/hie_hvg_canonical.txt
#       Benchmark_Hie_Out/hie_hvg_canonical.md5
#       Benchmark_Hie_Out/hie_hvg_canonical_metadata.json
#   - Preserves canonical HVG order exactly.
#   - Uses fixed batch key 'tech' when present, matching the HIE master
#     benchmark and make_hie_canonical_hvg.py.
#   - Exports the Online iNMF H embedding with rows aligned to AnnData
#     obs_names so bench_hie_master_canonical_v7.py can load it safely.
#   - Uses strict pancreas/mouse-style H alignment:
#       retrieve H/H.norm, coerce to cells x factors, assign canonical
#       cell IDs when rliger row/column names are non-canonical but
#       dimensions match, and stop rather than writing an incomplete/NA file.
#
# INPUT:
#   ./Dataset/human_pancreas_norm_complexBatch.h5ad
#   ./Benchmark_Hie_Out/hie_hvg_canonical.txt
#
# OUTPUT:
#   ./Benchmark_Hie_Out/X_online_inmf_hie.csv
#   ./Benchmark_Hie_Out/online_inmf_hie_hvg_used.txt
#   ./Benchmark_Hie_Out/online_inmf_hie_hvg_used.md5
#   ./Benchmark_Hie_Out/X_online_inmf_hie_removed_cells.txt  (only if removed)
# ============================================================

suppressPackageStartupMessages({
  library(rliger)
  library(Matrix)
  library(zellkonverter)
  library(SingleCellExperiment)
})

set.seed(0)

# ---------------------------
# Config
# ---------------------------
# Optional override from PowerShell/R shell:
#   $env:GENOREFINE_DATASET_ROOT="C:/path/to/HIEDataset"
BASE_DIR <- Sys.getenv(
  "GENOREFINE_DATASET_ROOT",
  unset = getwd()
)
if (dir.exists(BASE_DIR)) {
  setwd(BASE_DIR)
} else {
  message("BASE_DIR not found. Using current working directory: ", getwd())
}

DATA_FILE <- "./Dataset/human_pancreas_norm_complexBatch.h5ad"
OUTPUT_FOLDER <- "./Benchmark_Hie_Out"
dir.create(OUTPUT_FOLDER, showWarnings = FALSE, recursive = TRUE)

OUT_CSV <- file.path(OUTPUT_FOLDER, "X_online_inmf_hie.csv")
OUT_HVG_USED_TXT <- file.path(OUTPUT_FOLDER, "online_inmf_hie_hvg_used.txt")
OUT_HVG_USED_MD5 <- file.path(OUTPUT_FOLDER, "online_inmf_hie_hvg_used.md5")
OUT_REMOVED_CELLS <- file.path(OUTPUT_FOLDER, "X_online_inmf_hie_removed_cells.txt")

CANONICAL_HVG_FILE <- file.path(OUTPUT_FOLDER, "hie_hvg_canonical.txt")
CANONICAL_HVG_MD5  <- file.path(OUTPUT_FOLDER, "hie_hvg_canonical.md5")
CANONICAL_HVG_META <- file.path(OUTPUT_FOLDER, "hie_hvg_canonical_metadata.json")

FIXED_BATCH_KEY <- "tech"
BATCH_KEY_CANDIDATES <- c("tech", "technology", "platform", "protocol", "method", "batch", "Batch", "dataset", "study", "donor", "orig.ident", "source")
LABEL_KEY_CANDIDATES <- c("celltype", "class", "cell_type", "CellType", "label", "labels", "annotation")

K_FACTORS <- 30
LAMBDA <- 5.0
MIN_SHARED_GENES <- 500
MIN_CELLS_PER_BATCH <- 10

# If TRUE, fail if any cells are filtered out before Online iNMF. This prevents
# Python from silently loading an incomplete embedding.
STRICT_NO_REMOVED_CELLS <- TRUE

# ---------------------------
# Helpers
# ---------------------------
to_dgC <- function(x) {
  if (!inherits(x, "dgCMatrix")) x <- as(x, "dgCMatrix")
  x
}

pick_key <- function(df, fixed, candidates) {
  if (!is.null(fixed) && fixed %in% colnames(df)) return(fixed)
  for (k in candidates) {
    if (k %in% colnames(df)) return(k)
  }
  return(NA_character_)
}

read_h5ad_compat <- function(path) {
  attempts <- list(
    function() zellkonverter::readH5AD(path, reader = "R", use_hdf5 = TRUE),
    function() zellkonverter::readH5AD(path, use_hdf5 = TRUE),
    function() zellkonverter::readH5AD(path, reader = "R"),
    function() zellkonverter::readH5AD(path)
  )

  errs <- character(0)
  for (fun in attempts) {
    out <- tryCatch(fun(), error = function(e) {
      errs <<- c(errs, conditionMessage(e))
      NULL
    })
    if (!is.null(out)) return(out)
  }
  stop("All zellkonverter::readH5AD() attempts failed.\n", paste(unique(errs), collapse = "\n"))
}

get_counts_matrix <- function(sce) {
  assay_names <- assayNames(sce)
  message("Assays available: ", paste(assay_names, collapse = ", "))
  if ("counts" %in% assay_names) return(assay(sce, "counts"))
  if ("X" %in% assay_names) return(assay(sce, "X"))
  if ("logcounts" %in% assay_names) return(assay(sce, "logcounts"))
  assay(sce, assay_names[1])
}

compute_gene_md5 <- function(genes) {
  genes <- as.character(genes)
  genes <- trimws(genes)
  genes <- genes[!is.na(genes)]
  genes <- genes[nzchar(genes)]
  payload <- paste(genes, collapse = "\n")

  tf <- tempfile(fileext = ".txt")
  con <- file(tf, open = "wb")
  on.exit({
    try(close(con), silent = TRUE)
    unlink(tf)
  }, add = TRUE)

  writeChar(payload, con, eos = NULL, useBytes = TRUE)
  close(con)
  unname(tools::md5sum(tf))
}

read_canonical_hvgs <- function(path) {
  if (!file.exists(path)) stop("Canonical HVG file not found: ", path)
  genes <- readLines(path, warn = FALSE)
  genes <- as.character(genes)
  genes <- trimws(genes)
  genes <- genes[!is.na(genes)]
  genes <- genes[nzchar(genes)]
  genes <- genes[!duplicated(genes)]
  genes
}

get_var_features_compat <- function(lig) {
  out <- NULL
  try({ out <- varFeatures(lig) }, silent = TRUE)
  if (is.null(out) && "var.genes" %in% slotNames(lig)) out <- lig@var.genes
  out <- unique(as.character(out))
  out <- out[!is.na(out)]
  out
}

set_var_features_compat <- function(lig, genes) {
  genes <- unique(as.character(genes))
  genes <- genes[!is.na(genes)]
  ok <- FALSE
  try({ varFeatures(lig) <- genes; ok <- TRUE }, silent = TRUE)
  if (!ok && "var.genes" %in% slotNames(lig)) {
    lig@var.genes <- genes
    ok <- TRUE
  }
  if (!ok) stop("Could not set variable features on liger object.")
  lig
}

get_raw_list_compat <- function(lig) {
  out <- NULL
  try({ out <- rawData(lig) }, silent = TRUE)
  if (is.null(out)) {
    try({ out <- getMatrix(lig, "rawData") }, silent = TRUE)
  }
  if (is.null(out) && "raw.data" %in% slotNames(lig)) out <- lig@raw.data
  out
}

run_online_inmf_compat <- function(lig, k, lambda) {
  out <- NULL

  # rliger v2.x preferred route
  try({ out <- runIntegration(lig, k = k, lambda = lambda, method = "online") }, silent = TRUE)

  # older fallbacks
  if (is.null(out)) {
    try({ out <- runOnlineINMF(lig, k = k, lambda = lambda) }, silent = TRUE)
  }
  if (is.null(out)) {
    try({ out <- online_iNMF(lig, k = k, lambda = lambda) }, silent = TRUE)
  }
  if (is.null(out)) stop("Could not run online iNMF using runIntegration/runOnlineINMF/online_iNMF.")
  out
}

quantile_norm_compat <- function(lig) {
  out <- NULL
  try({ out <- quantileNorm(lig) }, silent = TRUE)
  if (is.null(out)) {
    try({ out <- quantile_norm(lig) }, silent = TRUE)
  }
  if (is.null(out)) stop("Could not run quantile normalization using quantileNorm/quantile_norm.")
  out
}

get_H_list_compat <- function(lig) {
  # Primary: export H, matching pancreas Online iNMF script. Fall back to H.norm.
  out <- NULL
  try({ out <- getMatrix(lig, "H") }, silent = TRUE)
  if (is.null(out) && "H" %in% slotNames(lig)) {
    try({ out <- lig@H }, silent = TRUE)
  }
  if (is.null(out)) {
    try({ out <- getMatrix(lig, "H.norm") }, silent = TRUE)
  }
  if (is.null(out) && "H.norm" %in% slotNames(lig)) {
    try({ out <- lig@H.norm }, silent = TRUE)
  }
  if (is.null(out)) stop("Could not retrieve H or H.norm from liger object.")
  if (inherits(out, "list")) return(out)
  list(all = out)
}

coerce_H_to_cells_by_k <- function(h, expected_cells, batch_name) {
  h <- as.matrix(h)
  rn <- rownames(h)
  cn <- colnames(h)
  n_expected <- length(expected_cells)

  assign_factor_names <- function(m) {
    if (is.null(colnames(m)) || any(is.na(colnames(m))) || any(colnames(m) == "")) {
      colnames(m) <- paste0("Factor_", seq_len(ncol(m)))
    }
    m
  }

  # Best case: rows are cell IDs.
  if (!is.null(rn) && all(expected_cells %in% rn)) {
    h <- h[expected_cells, , drop = FALSE]
    h <- assign_factor_names(h)
    return(h)
  }

  # Best case: columns are cell IDs; transpose to cells x factors.
  if (!is.null(cn) && all(expected_cells %in% cn)) {
    h <- t(h[, expected_cells, drop = FALSE])
    rownames(h) <- expected_cells
    h <- assign_factor_names(h)
    return(h)
  }

  # If names are missing/non-canonical but dimensions match, assume rliger kept order.
  if (nrow(h) == n_expected) {
    if (!is.null(rn) && length(rn) == n_expected && setequal(rn, expected_cells)) {
      h <- h[expected_cells, , drop = FALSE]
    } else {
      message("Warning: H rownames for batch '", batch_name, "' are missing or non-canonical; assuming row order matches expected cell order.")
      rownames(h) <- expected_cells
    }
    h <- assign_factor_names(h)
    return(h)
  }

  if (ncol(h) == n_expected) {
    if (!is.null(cn) && length(cn) == n_expected && setequal(cn, expected_cells)) {
      h <- t(h[, expected_cells, drop = FALSE])
    } else {
      message("Warning: H colnames for batch '", batch_name, "' are missing or non-canonical; assuming column order matches expected cell order and transposing.")
      h <- t(h)
    }
    rownames(h) <- expected_cells
    h <- assign_factor_names(h)
    return(h)
  }

  stop(
    "Could not align H matrix for batch '", batch_name, "'. Expected ", n_expected,
    " cells, but H dim=", paste(dim(h), collapse = "x")
  )
}

# ---------------------------
# 1) Load H5AD
# ---------------------------
message("Reading H5AD: ", DATA_FILE)
if (!file.exists(DATA_FILE)) stop("Missing file: ", DATA_FILE)

sce <- read_h5ad_compat(DATA_FILE)
expr <- get_counts_matrix(sce)
expr <- to_dgC(expr)

meta <- as.data.frame(colData(sce))
cell_ids <- colnames(expr)
if (is.null(cell_ids)) stop("No cell IDs (colnames) found. Cannot align to Python.")
row.names(meta) <- cell_ids

gene_ids <- rownames(expr)
if (is.null(gene_ids)) stop("No gene IDs (rownames) found. Cannot proceed safely.")

batch_key <- pick_key(meta, FIXED_BATCH_KEY, BATCH_KEY_CANDIDATES)
if (is.na(batch_key)) {
  stop(
    "Could not detect a batch key in colData. Tried fixed='", FIXED_BATCH_KEY,
    "' and candidates: ", paste(BATCH_KEY_CANDIDATES, collapse = ", "),
    "\nAvailable colData keys (first 40): ", paste(head(colnames(meta), 40), collapse = ", ")
  )
}
message("Using batch key: ", batch_key)

label_key <- pick_key(meta, NULL, LABEL_KEY_CANDIDATES)
if (!is.na(label_key)) message("Found label key (optional): ", label_key)

batch_vals <- as.character(meta[[batch_key]])
if (any(is.na(batch_vals))) stop("Batch column has NA values; please clean or choose another batch key.")
names(batch_vals) <- cell_ids

batch_levels <- unique(batch_vals)
message("Detected batches: ", length(batch_levels))
message("Batch levels: ", paste(batch_levels, collapse = ", "))

# ---------------------------
# 2) Split into batches as sparse matrices (genes x cells)
# ---------------------------
mat_list <- list()
cell_order_by_batch <- list()

for (b in batch_levels) {
  idx <- which(batch_vals == b)
  if (length(idx) == 0) next

  if (length(idx) < MIN_CELLS_PER_BATCH) {
    message("Skipping tiny batch '", b, "' with n=", length(idx), " (<", MIN_CELLS_PER_BATCH, ")")
    next
  }

  m <- expr[, idx, drop = FALSE]
  m <- to_dgC(m)
  rownames(m) <- gene_ids
  if (is.null(colnames(m))) colnames(m) <- cell_ids[idx]

  mat_list[[b]] <- m
  cell_order_by_batch[[b]] <- colnames(m)
}

if (length(mat_list) < 2) stop("Need >=2 batches for online iNMF. Found: ", length(mat_list))

batch_names_used <- names(mat_list)
message("Cells per batch before filtering:")
print(sapply(mat_list, ncol))

# ---------------------------
# 3) Enforce shared genes and canonical HVGs
# ---------------------------
gene_sets <- lapply(mat_list, rownames)
shared_genes <- Reduce(intersect, gene_sets)
shared_genes <- unique(as.character(shared_genes))
shared_genes <- shared_genes[!is.na(shared_genes)]
message("Shared genes across kept batches: ", length(shared_genes))

if (length(shared_genes) < MIN_SHARED_GENES) {
  stop("Too few shared genes across batches: ", length(shared_genes), " (MIN_SHARED_GENES=", MIN_SHARED_GENES, ")")
}
mat_list <- lapply(mat_list, function(m) m[shared_genes, , drop = FALSE])

message("Loading canonical HVGs from: ", CANONICAL_HVG_FILE)
canonical_genes <- read_canonical_hvgs(CANONICAL_HVG_FILE)
message("Canonical HVGs loaded: ", length(canonical_genes))

loaded_md5 <- compute_gene_md5(canonical_genes)
message("Loaded canonical HVG md5: ", loaded_md5)
if (file.exists(CANONICAL_HVG_MD5)) {
  expected_md5 <- readLines(CANONICAL_HVG_MD5, warn = FALSE)
  expected_md5 <- expected_md5[nzchar(expected_md5)][1]
  if (!is.na(expected_md5) && nzchar(expected_md5)) {
    message("Expected canonical HVG md5: ", expected_md5)
    if (!identical(expected_md5, loaded_md5)) {
      warning("Canonical HVG md5 mismatch. Expected: ", expected_md5, " Loaded: ", loaded_md5)
    }
  }
} else {
  writeLines(loaded_md5, CANONICAL_HVG_MD5)
  message("Wrote canonical HVG md5 file: ", CANONICAL_HVG_MD5)
}

if (file.exists(CANONICAL_HVG_META)) {
  message("Found canonical metadata file: ", CANONICAL_HVG_META)
}

missing_canonical <- setdiff(canonical_genes, shared_genes)
if (length(missing_canonical) > 0) {
  stop(
    "Canonical HVG file contains genes not present in shared feature space. Missing=", length(missing_canonical),
    "; examples: ", paste(head(missing_canonical, 10), collapse = ", ")
  )
}

selected_genes <- canonical_genes[canonical_genes %in% shared_genes]
selected_genes <- unique(as.character(selected_genes))
selected_genes <- selected_genes[!is.na(selected_genes)]
message("Canonical HVGs matched shared genes: ", length(selected_genes))

if (length(selected_genes) < MIN_SHARED_GENES) {
  stop("Too few canonical HVGs matched shared feature space: ", length(selected_genes))
}

# Restrict all batches to selected genes, preserving canonical order.
mat_list <- lapply(mat_list, function(m) m[selected_genes, , drop = FALSE])

# Remove cells with 0 counts across selected genes.
removed_zero_cells <- character(0)
for (b in names(mat_list)) {
  nz <- Matrix::colSums(mat_list[[b]] != 0)
  keep <- (nz > 0)
  if (sum(!keep) > 0) {
    message("Removing ", sum(!keep), " cells with 0 counts across canonical genes in ", b, ".")
    removed_zero_cells <- c(removed_zero_cells, colnames(mat_list[[b]])[!keep])
    mat_list[[b]] <- mat_list[[b]][, keep, drop = FALSE]
  }
}

if (length(removed_zero_cells) > 0) {
  writeLines(removed_zero_cells, OUT_REMOVED_CELLS)
  message("Wrote removed cell list: ", OUT_REMOVED_CELLS)
  if (STRICT_NO_REMOVED_CELLS) {
    stop("Removed cells were detected before Online iNMF (", length(removed_zero_cells), "). This would make the exported embedding incomplete.")
  }
}

# Remove batches that became too small after filtering.
valid_batches <- character(0)
for (b in names(mat_list)) {
  if (ncol(mat_list[[b]]) >= MIN_CELLS_PER_BATCH) {
    valid_batches <- c(valid_batches, b)
  } else {
    message("Dropping batch after filtering because it has < ", MIN_CELLS_PER_BATCH, " cells: ", b)
  }
}
mat_list <- mat_list[valid_batches]
cell_order_by_batch <- cell_order_by_batch[valid_batches]
batch_names_used <- names(mat_list)

if (length(mat_list) < 2) stop("Need >=2 usable batches after canonical-HVG filtering. Found: ", length(mat_list))

message("Cells per batch after filtering:")
print(sapply(mat_list, ncol))

all_cells_by_batch <- lapply(mat_list, colnames)
all_cells_by_batch <- all_cells_by_batch[batch_names_used]
all_cells_in_liger_order <- unlist(all_cells_by_batch, use.names = FALSE)
cell_ids_final <- cell_ids[!(cell_ids %in% removed_zero_cells)]

# ---------------------------
# 4) Create LIGER object and set canonical variable features
# ---------------------------
message("Creating liger object...")
lig <- createLiger(mat_list)

raw_list_after <- get_raw_list_compat(lig)
if (!is.null(raw_list_after)) {
  common_genes_after <- Reduce(intersect, lapply(raw_list_after, rownames))
} else {
  common_genes_after <- Reduce(intersect, lapply(mat_list, rownames))
}
common_genes_after <- unique(as.character(common_genes_after))
common_genes_after <- common_genes_after[!is.na(common_genes_after)]

missing_after <- setdiff(selected_genes, common_genes_after)
if (length(missing_after) > 0) {
  stop("Canonical selected genes are missing after LIGER object creation. Examples: ", paste(head(missing_after, 10), collapse = ", "))
}

selected_genes <- selected_genes[selected_genes %in% common_genes_after]
selected_genes <- unique(as.character(selected_genes))
selected_genes <- selected_genes[!is.na(selected_genes)]
message("Canonical HVGs present after createLiger: ", length(selected_genes))

if (length(selected_genes) < MIN_SHARED_GENES) {
  stop("Too few canonical genes remain after LIGER object creation: ", length(selected_genes))
}

writeLines(selected_genes, OUT_HVG_USED_TXT)
used_md5 <- compute_gene_md5(selected_genes)
writeLines(used_md5, OUT_HVG_USED_MD5)
message("Wrote exact HVG list used by rliger: ", OUT_HVG_USED_TXT)
message("Used HVG md5: ", used_md5)

lig <- set_var_features_compat(lig, selected_genes)
var_genes_now <- get_var_features_compat(lig)
message("Variable genes set to: ", length(var_genes_now))

if (K_FACTORS >= length(var_genes_now)) {
  stop("K_FACTORS (", K_FACTORS, ") must be < number of variable genes (", length(var_genes_now), ").")
}

# ---------------------------
# 5) Normalize, scale, Online iNMF, quantile normalization
# ---------------------------
message("normalize() ...")
lig <- normalize(lig)

message("scaleNotCenter() ...")
lig <- scaleNotCenter(lig)

message("Online iNMF(k=", K_FACTORS, ", lambda=", LAMBDA, ") ...")
lig <- run_online_inmf_compat(lig, k = K_FACTORS, lambda = LAMBDA)

message("Quantile normalization ...")
lig <- quantile_norm_compat(lig)

# ---------------------------
# 6) Export H/H.norm embedding aligned to original AnnData obs_names
# ---------------------------
message("Exporting H embedding using strict pancreas/mouse-style alignment...")

H_raw_list <- get_H_list_compat(lig)

# If H is returned as list, align each batch. If a single matrix, align against all expected cells.
if (length(H_raw_list) == length(batch_names_used) && !("all" %in% names(H_raw_list))) {
  if (is.null(names(H_raw_list)) || any(names(H_raw_list) == "")) {
    names(H_raw_list) <- batch_names_used
  }

  if (!all(batch_names_used %in% names(H_raw_list))) {
    message("Warning: H list names do not match batch names; assuming H list order matches batch_names_used.")
    names(H_raw_list) <- batch_names_used
  }

  H_list <- list()
  for (b in batch_names_used) {
    H_list[[b]] <- coerce_H_to_cells_by_k(
      H_raw_list[[b]],
      expected_cells = all_cells_by_batch[[b]],
      batch_name = b
    )
  }
  H <- do.call(rbind, H_list[batch_names_used])
} else {
  H <- coerce_H_to_cells_by_k(
    H_raw_list[[1]],
    expected_cells = all_cells_in_liger_order,
    batch_name = "all_batches"
  )
}

if (is.null(rownames(H))) stop("H has no rownames after coercion; cannot align cells.")

missing <- setdiff(cell_ids_final, rownames(H))
extra <- setdiff(rownames(H), cell_ids_final)

message("Cells in original AnnData: ", length(cell_ids))
message("Cells expected after filtering: ", length(cell_ids_final))
message("Cells in H: ", nrow(H))
message("Missing cells in H: ", length(missing))
message("Extra cells in H: ", length(extra))

if (length(missing) > 0) {
  stop("H is missing expected cells. Example missing: ", paste(head(missing, 10), collapse = ", "))
}
if (length(extra) > 0) {
  message("Warning: H has extra cells not expected (showing up to 10): ", paste(head(extra, 10), collapse = ", "))
}

# Reorder to original AnnData obs_names.
H <- H[cell_ids_final, , drop = FALSE]

if (any(!is.finite(H))) {
  stop("Final H contains NA/Inf values. Refusing to write invalid embedding CSV.")
}

if (nrow(H) != length(cell_ids)) {
  stop(
    "Final H row count (", nrow(H), ") does not match original AnnData cells (", length(cell_ids), "). ",
    "This would fail or partially zero-fill in Python."
  )
}

write.csv(H, OUT_CSV, quote = FALSE)
message("✅ Online iNMF complete using HIE canonical HVGs. Wrote: ", OUT_CSV)
message("Final embedding dim: ", paste(dim(H), collapse = "x"))
message("Final embedding variance: ", signif(var(as.vector(H)), 6))
message("Batch key used: ", batch_key)
