# ============================================================
# FILE: seurat_integration_hie_canonical_v5.R
# PURPOSE:
#   Run Seurat integration on the HIE (.h5ad) benchmark using the
#   frozen canonical HIE HVG file generated by make_hie_canonical_hvg.py.
#
# CANONICAL CONSISTENCY
#   - Uses ./Benchmark_Hie_Out/hie_hvg_canonical.txt by default.
#   - Preserves canonical HVG order exactly.
#   - Uses fixed batch key 'tech' when present, matching the HIE Python master.
#   - Exports PCA embedding rows aligned exactly to AnnData obs_names.
#   - Stops if alignment fails or if the exported matrix contains NA/Inf.
#
# INPUT:
#   ./Dataset/human_pancreas_norm_complexBatch.h5ad
#   ./Benchmark_Hie_Out/hie_hvg_canonical.txt
#   ./Benchmark_Hie_Out/hie_hvg_canonical.md5       (optional check)
#
# OUTPUT:
#   ./Benchmark_Hie_Out/X_seurat_hie.csv
#   ./Benchmark_Hie_Out/seurat_hie_hvg_used.txt
#   ./Benchmark_Hie_Out/seurat_hie_hvg_used.md5
# ============================================================

suppressPackageStartupMessages({
  library(Seurat)
  library(Matrix)
  library(zellkonverter)
  library(SingleCellExperiment)
})

set.seed(0)

# -----------------------------
# CONFIG
# -----------------------------
BASE_DIR <- Sys.getenv("GENOREFINE_DATASET_ROOT", unset = getwd())

if (dir.exists(BASE_DIR)) {
  setwd(BASE_DIR)
} else {
  message("BASE_DIR not found: ", BASE_DIR)
  message("Using current working directory: ", getwd())
}

IN_H5AD <- "./Dataset/human_pancreas_norm_complexBatch.h5ad"
OUT_DIR <- "./Benchmark_Hie_Out"
dir.create(OUT_DIR, showWarnings = FALSE, recursive = TRUE)

OUT_CSV <- file.path(OUT_DIR, "X_seurat_hie.csv")
OUT_HVG_USED_TXT <- file.path(OUT_DIR, "seurat_hie_hvg_used.txt")
OUT_HVG_USED_MD5 <- file.path(OUT_DIR, "seurat_hie_hvg_used.md5")
OUT_REMOVED_CELLS <- file.path(OUT_DIR, "X_seurat_hie_removed_cells.txt")

FIXED_BATCH_KEY <- "tech"
PREFERRED_BATCH_KEYS <- c("tech", "batch", "Batch", "dataset", "study", "donor", "orig.ident", "source")
LABEL_KEY_CANDIDATES <- c("celltype", "cell_type", "cell_ontology_class", "class", "CellType", "label", "labels", "annotation")

N_PCS <- 50
ANCHOR_DIMS <- 30
MIN_BATCH_CELLS <- 5
MIN_GENES_REQUIRED <- 500

USE_CANONICAL_HVG_FILE <- TRUE
CANONICAL_HVG_FILE <- file.path(OUT_DIR, "hie_hvg_canonical.txt")
CANONICAL_HVG_MD5 <- file.path(OUT_DIR, "hie_hvg_canonical.md5")
FALLBACK_TO_FAIR_HVGS_IF_MISSING <- FALSE
REQUIRE_EXACT_CANONICAL_HVG_MATCH <- TRUE

# Legacy fallback; used only if FALLBACK_TO_FAIR_HVGS_IF_MISSING=TRUE.
N_VAR_GENES_PER_BATCH <- 2000
N_VAR_GENES_FINAL <- 3000

# -----------------------------
# Helpers
# -----------------------------
pick_batch_key <- function(md, preferred_keys) {
  existing <- preferred_keys[preferred_keys %in% colnames(md)]
  if (length(existing) == 0) return(NA_character_)
  for (k in existing) {
    vals <- md[[k]]
    vals <- vals[!is.na(vals)]
    if (length(unique(as.character(vals))) >= 2) return(k)
  }
  existing[1]
}

get_celltype_column <- function(md) {
  hit <- LABEL_KEY_CANDIDATES[LABEL_KEY_CANDIDATES %in% colnames(md)]
  if (length(hit) == 0) return(NA_character_)
  hit[1]
}

safe_as_dgC <- function(x) {
  if (!inherits(x, "dgCMatrix")) x <- as(x, "dgCMatrix")
  x
}

get_counts_matrix <- function(sce) {
  assay_names <- assayNames(sce)
  cat("Assays found:", paste(assay_names, collapse = ", "), "\n")
  if ("counts" %in% assay_names) return(assay(sce, "counts"))
  if ("X" %in% assay_names) return(assay(sce, "X"))
  if ("logcounts" %in% assay_names) return(assay(sce, "logcounts"))
  assay(sce, assay_names[1])
}

read_h5ad_compat <- function(path) {
  attempts <- list(
    function() zellkonverter::readH5AD(path, reader = "R", use_hdf5 = TRUE),
    function() zellkonverter::readH5AD(path, use_hdf5 = TRUE),
    function() zellkonverter::readH5AD(path, reader = "R"),
    function() zellkonverter::readH5AD(path)
  )

  errors <- character(0)
  for (fn in attempts) {
    out <- tryCatch(fn(), error = function(e) {
      errors <<- c(errors, conditionMessage(e))
      NULL
    })
    if (!is.null(out)) return(out)
  }

  stop("All zellkonverter::readH5AD() attempts failed.\n", paste(unique(errors), collapse = "\n"))
}

read_canonical_hvgs <- function(path) {
  if (!file.exists(path)) stop("Canonical HVG file not found: ", path)
  hvgs <- readLines(path, warn = FALSE)
  hvgs <- trimws(hvgs)
  hvgs <- hvgs[nzchar(hvgs)]
  hvgs <- unique(as.character(hvgs))
  hvgs <- hvgs[!is.na(hvgs)]
  hvgs
}

compute_gene_md5 <- function(genes) {
  genes <- as.character(genes)
  genes <- genes[!is.na(genes)]
  payload <- paste(genes, collapse = "\n")

  tf <- tempfile(fileext = ".txt")
  con <- file(tf, open = "wb")
  on.exit({
    try(close(con), silent = TRUE)
    unlink(tf)
  }, add = TRUE)

  writeChar(payload, con, eos = NULL, useBytes = TRUE)
  close(con)
  unname(tools::md5sum(tf))
}

normalize_cell_name <- function(x) {
  x <- as.character(x)
  x <- sub("-1$", "", x)
  x <- sub("\\.1$", "", x)
  x <- gsub("\\.", "-", x)
  x
}

align_embedding_to_cell_ids <- function(embedding, target_cell_ids) {
  embedding <- as.matrix(embedding)
  if (is.null(rownames(embedding))) {
    stop("Embedding has NULL rownames; cannot align to AnnData obs_names.")
  }
  if (is.null(colnames(embedding))) {
    colnames(embedding) <- paste0("PC_", seq_len(ncol(embedding)))
  }

  # Direct alignment.
  direct_idx <- match(target_cell_ids, rownames(embedding))
  direct_ok <- !is.na(direct_idx)
  direct_rate <- mean(direct_ok)
  cat("Seurat PCA direct cell alignment rate:", direct_rate, "\n")

  if (direct_rate >= 0.999) {
    out <- embedding[direct_idx, , drop = FALSE]
    rownames(out) <- target_cell_ids
    return(out)
  }

  # Normalized alignment to handle minor cell-name differences.
  target_norm <- normalize_cell_name(target_cell_ids)
  emb_norm <- normalize_cell_name(rownames(embedding))
  if (any(duplicated(emb_norm))) {
    dup_n <- sum(duplicated(emb_norm))
    warning("Normalized embedding rownames contain duplicates: ", dup_n, ". Cannot use normalized alignment.")
  } else {
    norm_idx <- match(target_norm, emb_norm)
    norm_ok <- !is.na(norm_idx)
    norm_rate <- mean(norm_ok)
    cat("Seurat PCA normalized cell alignment rate:", norm_rate, "\n")

    if (norm_rate >= 0.999) {
      out <- embedding[norm_idx, , drop = FALSE]
      rownames(out) <- target_cell_ids
      return(out)
    }
  }

  missing_direct <- target_cell_ids[!direct_ok]
  stop(
    "Seurat PCA embedding alignment failed. Direct match rate=", round(direct_rate * 100, 2), "%. ",
    "Examples missing: ", paste(head(missing_direct, 10), collapse = ", ")
  )
}

select_fair_hvgs_fallback <- function(mat_list, n_per_batch, n_final) {
  cat("Selecting HVGs per batch (fallback fair union)...\n")
  hvg_lists <- list()

  for (b in names(mat_list)) {
    cat("  - batch:", b, "cells:", ncol(mat_list[[b]]), "\n")
    if (ncol(mat_list[[b]]) < MIN_BATCH_CELLS) {
      stop("Batch too small for fallback HVG selection: ", b)
    }
    if (length(mat_list[[b]]@x) > 0) {
      mat_list[[b]]@x[mat_list[[b]]@x < 0] <- 0
    }

    tmp <- CreateSeuratObject(counts = mat_list[[b]], project = paste0("HIE_", b))
    tmp <- NormalizeData(tmp, verbose = FALSE)
    tmp <- FindVariableFeatures(tmp, selection.method = "vst", nfeatures = n_per_batch, verbose = FALSE)
    hvg_lists[[b]] <- VariableFeatures(tmp)
  }

  all_hvgs <- unlist(hvg_lists, use.names = FALSE)
  if (length(all_hvgs) == 0) stop("No fallback HVGs were selected.")
  hvg_freq <- sort(table(all_hvgs), decreasing = TRUE)
  selected <- names(hvg_freq)
  if (length(selected) > n_final) selected <- selected[seq_len(n_final)]
  selected <- unique(as.character(selected))
  selected[!is.na(selected)]
}

# -----------------------------
# 1) Load AnnData (.h5ad)
# -----------------------------
cat("Working directory:", getwd(), "\n")
cat("Reading:", IN_H5AD, "\n")
if (!file.exists(IN_H5AD)) stop("Missing file: ", IN_H5AD)

sce <- read_h5ad_compat(IN_H5AD)
counts <- get_counts_matrix(sce)
counts <- safe_as_dgC(counts)

md <- as.data.frame(colData(sce))
cell_ids <- colnames(counts)
if (is.null(cell_ids)) stop("Counts matrix has NULL colnames; cannot align embeddings.")

gene_names <- rownames(counts)
if (is.null(gene_names)) stop("Counts matrix has NULL rownames; cannot run Seurat integration safely.")

rownames(md) <- cell_ids

if (!("method" %in% colnames(md)) && ("dataset" %in% colnames(md))) md$method <- as.character(md$dataset)
if (!("study" %in% colnames(md)) && ("dataset" %in% colnames(md))) md$study <- as.character(md$dataset)

if (FIXED_BATCH_KEY %in% colnames(md)) {
  BATCH_KEY <- FIXED_BATCH_KEY
} else {
  BATCH_KEY <- pick_batch_key(md, PREFERRED_BATCH_KEYS)
}
if (is.na(BATCH_KEY) || is.null(BATCH_KEY)) {
  stop("No valid batch key found. Available keys: ", paste(colnames(md), collapse = ", "))
}
cat("Using batch key:", BATCH_KEY, "\n")

celltype_col <- get_celltype_column(md)
if (!is.na(celltype_col)) cat("Using optional label key:", celltype_col, "\n")

# -----------------------------
# 2) Split by batch
# -----------------------------
batches <- as.character(md[[BATCH_KEY]])
names(batches) <- cell_ids
if (any(is.na(batches))) stop("Batch column contains NA values.")

batch_levels <- sort(unique(batches))
cat("Number of batches:", length(batch_levels), "\n")
if (length(batch_levels) < 2) stop("Need >=2 batches for Seurat integration. Found: ", length(batch_levels))

mat_list <- lapply(batch_levels, function(b) {
  idx <- which(batches == b)
  counts[, idx, drop = FALSE]
})
names(mat_list) <- batch_levels

for (b in names(mat_list)) {
  mat_list[[b]] <- safe_as_dgC(mat_list[[b]])
  rownames(mat_list[[b]]) <- gene_names
  if (is.null(colnames(mat_list[[b]]))) colnames(mat_list[[b]]) <- names(batches)[batches == b]
}

cat("Cells per batch:\n")
print(sapply(mat_list, ncol))

small_batches <- names(mat_list)[sapply(mat_list, ncol) < MIN_BATCH_CELLS]
if (length(small_batches) > 0) {
  stop("Batches below MIN_BATCH_CELLS were found: ", paste(small_batches, collapse = ", "))
}

# -----------------------------
# 3) Canonical HVG selection
# -----------------------------
cat("Selecting variable genes...\n")

if (isTRUE(USE_CANONICAL_HVG_FILE)) {
  if (file.exists(CANONICAL_HVG_FILE)) {
    cat("Using canonical HVG file:", CANONICAL_HVG_FILE, "\n")
    canonical_hvgs <- read_canonical_hvgs(CANONICAL_HVG_FILE)
    cat("Canonical HVGs loaded:", length(canonical_hvgs), "\n")

    loaded_md5 <- compute_gene_md5(canonical_hvgs)
    cat("Loaded canonical HVG md5:", loaded_md5, "\n")
    if (file.exists(CANONICAL_HVG_MD5)) {
      expected_md5 <- readLines(CANONICAL_HVG_MD5, warn = FALSE)
      expected_md5 <- expected_md5[nzchar(expected_md5)][1]
      if (!is.na(expected_md5) && nzchar(expected_md5)) {
        cat("Expected canonical HVG md5:", expected_md5, "\n")
        if (!identical(expected_md5, loaded_md5)) {
          warning("Canonical HVG md5 mismatch. Expected=", expected_md5, " Loaded=", loaded_md5)
        }
      }
    }

    missing_from_data <- setdiff(canonical_hvgs, gene_names)
    if (isTRUE(REQUIRE_EXACT_CANONICAL_HVG_MATCH) && length(missing_from_data) > 0) {
      stop(
        "Canonical HVG file contains genes not present in the dataset. Missing=", length(missing_from_data),
        "; examples: ", paste(head(missing_from_data, 10), collapse = ", ")
      )
    }

    selected_genes <- canonical_hvgs[canonical_hvgs %in% gene_names]
    selected_genes <- unique(as.character(selected_genes))
    selected_genes <- selected_genes[!is.na(selected_genes)]
    feature_selection_mode <- "canonical_file"
  } else {
    if (!FALLBACK_TO_FAIR_HVGS_IF_MISSING) stop("Canonical HVG file not found: ", CANONICAL_HVG_FILE)
    selected_genes <- select_fair_hvgs_fallback(mat_list, N_VAR_GENES_PER_BATCH, N_VAR_GENES_FINAL)
    feature_selection_mode <- "fallback_fair_hvg"
  }
} else {
  selected_genes <- select_fair_hvgs_fallback(mat_list, N_VAR_GENES_PER_BATCH, N_VAR_GENES_FINAL)
  feature_selection_mode <- "fallback_fair_hvg"
}

cat("Selected genes before shared-batch filtering:", length(selected_genes), "\n")
if (length(selected_genes) < MIN_GENES_REQUIRED) {
  stop("Too few selected genes after feature selection: ", length(selected_genes))
}

# Shared genes across batches, preserving canonical order.
shared_genes <- Reduce(intersect, lapply(mat_list, rownames))
selected_genes_use <- selected_genes[selected_genes %in% shared_genes]
selected_genes_use <- unique(as.character(selected_genes_use))
selected_genes_use <- selected_genes_use[!is.na(selected_genes_use)]
cat("Selected genes present in ALL batches:", length(selected_genes_use), "\n")

if (isTRUE(REQUIRE_EXACT_CANONICAL_HVG_MATCH) && identical(feature_selection_mode, "canonical_file") && length(selected_genes_use) != length(selected_genes)) {
  stop(
    "Canonical HVG list is not fully shared across batches. Selected=", length(selected_genes),
    " shared=", length(selected_genes_use)
  )
}
if (length(selected_genes_use) < MIN_GENES_REQUIRED) {
  stop("Too few selected genes shared across all batches: ", length(selected_genes_use))
}

writeLines(selected_genes_use, OUT_HVG_USED_TXT)
writeLines(compute_gene_md5(selected_genes_use), OUT_HVG_USED_MD5)
cat("Wrote Seurat HVG audit files:\n")
cat("  ", OUT_HVG_USED_TXT, "\n", sep = "")
cat("  ", OUT_HVG_USED_MD5, "\n", sep = "")

# Subset matrices in canonical order.
for (b in names(mat_list)) {
  mat_list[[b]] <- mat_list[[b]][selected_genes_use, , drop = FALSE]
}

# Strict check: no cells may be dropped, otherwise Python full-data benchmark cannot align exactly.
zero_cells <- character(0)
for (b in names(mat_list)) {
  nz <- Matrix::colSums(mat_list[[b]] != 0)
  zero_cells_b <- colnames(mat_list[[b]])[nz == 0]
  if (length(zero_cells_b) > 0) zero_cells <- c(zero_cells, zero_cells_b)
}
if (length(zero_cells) > 0) {
  writeLines(zero_cells, OUT_REMOVED_CELLS)
  stop(
    "Some cells have zero counts across canonical HVGs and would be dropped by Seurat. ",
    "Count=", length(zero_cells), ". Wrote list to ", OUT_REMOVED_CELLS,
    ". Update the Python benchmark to use the same cell subset or regenerate canonical HVGs."
  )
}

# -----------------------------
# 4) Create Seurat objects + integrate + PCA
# -----------------------------
cat("Creating Seurat objects...\n")
seurat_list <- list()

for (b in names(mat_list)) {
  obj <- CreateSeuratObject(counts = mat_list[[b]], project = paste0("HIE_", b))
  obj$batch <- b
  obj[[BATCH_KEY]] <- b

  if (!is.na(celltype_col)) {
    obj$celltype <- md[colnames(obj), celltype_col]
  }

  obj <- NormalizeData(obj, verbose = FALSE)
  VariableFeatures(obj) <- selected_genes_use[selected_genes_use %in% rownames(obj)]
  seurat_list[[b]] <- obj
}

# Ensure exact same feature order in all objects.
for (b in names(seurat_list)) {
  seurat_list[[b]] <- seurat_list[[b]][selected_genes_use, ]
  VariableFeatures(seurat_list[[b]]) <- selected_genes_use
}

anchor_dims_use <- min(ANCHOR_DIMS, length(selected_genes_use) - 1)
if (anchor_dims_use < 2) stop("anchor_dims_use became too small: ", anchor_dims_use)
cat("Using anchor dims: 1:", anchor_dims_use, "\n", sep = "")

cat("Finding integration anchors...\n")
anchors <- FindIntegrationAnchors(
  object.list = seurat_list,
  anchor.features = selected_genes_use,
  dims = 1:anchor_dims_use,
  verbose = TRUE
)

cat("Integrating data...\n")
seurat_integrated <- IntegrateData(anchorset = anchors, dims = 1:anchor_dims_use, verbose = TRUE)
DefaultAssay(seurat_integrated) <- "integrated"

cat("Scaling integrated assay...\n")
seurat_integrated <- ScaleData(seurat_integrated, verbose = FALSE)

npcs_use <- min(N_PCS, ncol(seurat_integrated) - 1, length(selected_genes_use) - 1)
if (npcs_use < 2) stop("npcs_use became too small: ", npcs_use)
cat("Running PCA with", npcs_use, "PCs...\n")
seurat_integrated <- RunPCA(seurat_integrated, npcs = npcs_use, verbose = FALSE)

# -----------------------------
# 5) Export embedding aligned to AnnData cell order
# -----------------------------
pca_coords <- Embeddings(seurat_integrated, reduction = "pca")
if (is.null(colnames(pca_coords))) colnames(pca_coords) <- paste0("PC_", seq_len(ncol(pca_coords)))

pca_aligned <- align_embedding_to_cell_ids(pca_coords, cell_ids)

if (nrow(pca_aligned) != length(cell_ids)) {
  stop("Aligned Seurat embedding row count does not match AnnData cells.")
}
if (any(!is.finite(pca_aligned))) {
  stop("Aligned Seurat embedding contains NA/Inf; refusing to write bad CSV.")
}
if (any(duplicated(rownames(pca_aligned)))) {
  stop("Aligned Seurat embedding contains duplicate rownames; refusing to write bad CSV.")
}

write.csv(pca_aligned, OUT_CSV, quote = FALSE)
cat("Cells in original AnnData:", length(cell_ids), "\n")
cat("Cells with embeddings:", nrow(pca_aligned), "\n")
cat("Cells removed / missing embeddings: 0\n")
cat("Wrote embedding CSV:", OUT_CSV, "\n")
cat("Feature selection mode:", feature_selection_mode, "\n")
cat("✅ Seurat integration complete using canonical HIE HVGs.\n")
