"""Reuse only a complete, verified, same-protocol standalone baseline evaluation."""

import json
from pathlib import Path
import shutil

from ..integrity import canonical_hash, file_fingerprint, project_path


def reuse_baseline(path, *, run, expected_config, expected_input, source_hash, current_runtime):
    path = Path(path).resolve()
    manifest = json.loads((path / "run.json").read_text(encoding="utf-8"))
    if manifest.get("status") != "succeeded" or manifest.get("kind") != "step3b_evaluation":
        raise ValueError("Baseline cache must be a completed evaluation")
    for relative, fingerprint in manifest["artifacts"].items():
        if file_fingerprint(project_path(path, relative)) != fingerprint:
            raise ValueError(f"Baseline cache changed: {relative}")
    read = lambda name: json.loads((path / name).read_text(encoding="utf-8"))
    cfg = read("config.json")
    if canonical_hash(cfg) != manifest["config_sha256"]:
        raise ValueError("Baseline cache configuration digest mismatch")
    for key in ("evaluation", "dataset", "store_manifest"):
        if canonical_hash(cfg[key]) != canonical_hash(expected_config[key]):
            raise ValueError(f"Baseline cache configuration mismatch: {key}")
    if len(cfg["embeddings"]) != 1 or cfg.get("refined_bundle"):
        raise ValueError("Baseline cache must contain only its standalone baseline")
    if read("embedding_0/input.json") != expected_input:
        raise ValueError("Baseline cache parent values/order/annotation provenance differs")
    if manifest.get("source_tree_sha256") != source_hash:
        raise ValueError("Baseline cache was generated by different source files/protocol documentation")
    if canonical_hash(read("runtime_start.json")) != canonical_hash(current_runtime):
        raise ValueError("Baseline cache runtime differs; regenerate explicitly")
    summary = read("summary.json")["evaluations"]
    if len(summary) != 1:
        raise ValueError("Invalid baseline summary")
    for relative, fingerprint in manifest["artifacts"].items():
        if relative.startswith("embedding_0/"):
            target = run.artifact_path(relative)
            shutil.copy2(project_path(path, relative), target)
            if file_fingerprint(target) != fingerprint:
                raise ValueError("Baseline cache changed during copying")
    record = dict(summary[0])
    record["timing"] = {"graph_seconds": 0.0, "grid_seconds": 0.0, "geometry_seconds": 0.0,
                        "reused_original_timing": summary[0]["timing"],
                        "note": "Zero new computation; cache validation/copy still contributes to run wall time"}
    record["cache"] = {"path": str(path), "manifest": file_fingerprint(path / "run.json")}
    return record
